### PR TITLE
Multi imu and mag support

### PR DESCRIPTION
**Pull request by KonradRudin**
Added support for multi mag and multi imu in a model.
Both sensors can have multiple instances, where each instance is published with a different id in mavlink.

PX4 side needs adaption to support multiple imus and magnetometer first, before this can be merged.

### CODE REVIEW

**Comment by KonradRudin** [comment]
@tstastny AND @Jaeyoung-Lim , this PR would be ready for review. I add the possibiltiy to simulate multiple IMUs and magnetometers. The sitl tests are failing, but because they can't properly check out the repo in the PX4 firmware to the right version. I don't know why this happens.

**Comment by Jaeyoung-Lim** [comment]
@KonradRudin Thanks! I will review the PR

The CI build tests have been fixed in https://github.com/PX4/PX4-SITL_gazebo/pull/907

Would you mind rebasing the PR on top?

**Review by Jaeyoung-Lim — APPROVED** [review]
Thanks! LGTM!

CI is broken on macOS, but not related to this PR

**Review by tstastny — APPROVED** [review]

**Comment by Jaeyoung-Lim** [comment]
This seems to have broken the multivehicle lockstep simulation for gazebo

**Comment by Jaeyoung-Lim** [comment]
@KonradRudin @tstastny This has significantly reduced the performance of the simulation due to switching the imu plugin to a sensor plugin, which in Gazebo uses a different lockstep thread. 

For example, previous implementation could simulate 200 vehicles on my desktop with realtime factor of 0.98, while after this change, simulating 3 vehicles of any vehicle type results in realtime factor of 0.6

I think what is happening is that the `mavlink_interface` enforces lockstep for the physics loop. but since the imu message is on the sensor lockstep, the physics lockstep on gazebo is significantly slowed down.

Would it be possible to revert at least the imu plugin to be a model plugin instead of a sensor plugin? Sorry that I overlooked this during the review

@dagar FYI, this might cause intermittent SITL failures

**Pull request merged**
