### PR TITLE
accumulate gyro measurements for opt flow msg

### PR DESCRIPTION
**Pull request by ChristophTobler**
This is how it is being done on other platforms (more robust against spikes).

### CODE REVIEW

**Comment by TSC21** [comment]
@ChristophTobler shound't this by applied also in the `gazebo_opticalFlow_plugin`?

**Comment by ChristophTobler** [comment]
@TSC21 The `gazebo_opticalFlow_plugin` already accumulates pixel flow (without gyro) and then sends the message which the `gazebo_mavlink_interface.cpp` subscribes to (this callback https://github.com/PX4/sitl_gazebo/pull/125/files#diff-af95b4649436828244349b1766ab5c46R816). In there we fill the gyro message that we accumulated over the same time.

**Comment by TSC21** [comment]
> @TSC21 The `gazebo_opticalFlow_plugin` already accumulates pixel flow (without gyro) and then sends the message which the `gazebo_mavlink_interface.cpp` subscribes to (this callback https://github.com/PX4/sitl_gazebo/pull/125/files#diff-af95b4649436828244349b1766ab5c46R816). In there we fill the gyro message that we accumulated over the same time.

Yeah it's a callback to it didn't saw that. Thanks.

**Comment by ChristophTobler** [comment]
@TSC21 Thanks!

**Pull request merged**
