### PR TITLE
Deflection of the BlueROV2 thrusters

### PR DESCRIPTION
**Pull request by lennartalff**
increased ODE solver iterations to avoid deflection of the thrusters.
Should solve issue #694

### CODE REVIEW

**Comment by timzarhansen** [comment]
This is much better and works great. 
Additionally, I think the movement seems to be more realistic. (while this is still far away)

Why is this not a problem for the Iris copter or the hippocampus? that's what I currently don't understand.

**Comment by lennartalff** [comment]
@Zarbokk I think it is about the motor count. If you remove for example thrusters 5-8, the first 4 thrusters behave well with the number of iterations still beeing 10.

**Comment by timzarhansen** [comment]
that could make sense. Additionally, I don't see a performance hit on my machine.

**Review by Jaeyoung-Lim — APPROVED** [review]
Since this is contained in the UUV bluerov simulation I think this is good

@lennartalff  Thanks for fixing this!

**Pull request merged**
