### PR TITLE
Magnetic field fix.

### PR DESCRIPTION
**Pull request by jgoppert**
This aligns north in gazebo which is (ENU) and qgroundcontrol.

### CODE REVIEW

**Comment by bkueng** [comment]
@jgoppert something is wrong with this, did you test fly it? It does not hold position after `commander takeoff`

**Comment by jgoppert** [comment]
Yes, I've test flown it. Which vehicle are you flying with? Also gps or optical flow? I've been on my own branch working on my matrice 100 model.  Without this it is clearly wrong. You can see that gazebo vehicle is aligned with east axis but compass says north in qgroundcontrol .

**Comment by jgoppert** [comment]
Since I've been flying primarily without gps, maybe the gps is also not in the correct frame?

**Comment by jgoppert** [comment]
I'll try it our on master and see what is going on.

**Comment by jgoppert** [comment]
See #44 .

**Pull request merged**
