### PR TITLE
update the motor failure plugin for ros2

### PR DESCRIPTION
**Pull request by stmoon**
The gazebo_motor_failure_plugin has been not used because of too old code, even though  the plugin is necessary for various studies like fault detection. 
So, I update the gazebo_motor_failure_plugin from ROS1 to ROS2.

### CODE REVIEW

**Review by Jaeyoung-Lim — APPROVED** [review]
Thanks! I think this is going in the right direction, although I would like to remove ROS dependency completely from this repository.

@stmoon Could you explain a bit more on the test setup and possibly document the use case with ROS2?
(We are also missing build tests for ROS2)

**Comment by stmoon** [comment]
Thanks!

### Test environment
I just used ROS2 (foxy) for the test. However, I think there is no dependency with other ros2 versions.
I tested it in px4_sitl_default

### Compile
- To use it, BUILD_ROS2_PLUGINS in cmake should be ON. (default is OFF).

### Publish for the test
- I followed the previous method with regard to the fault injection mechanism and topic name.... 
- To inject the fault to the motor, I used the command
```
$ ros2 topic pub --once /motor_failure/motor_number  std_msgs/msg/Int32 "{data: 1}"
```

**Comment by Jaeyoung-Lim** [comment]
@stmoon Great! Thanks! 

Would you also be able to add the test instruction on the PX4 user guide?

**Comment by stmoon** [comment]
@Jaeyoung-Lim Sure! Could you tell me which page do I write the test instruction?

**Comment by stmoon** [comment]
How is the PR going? any update?

**Comment by Jaeyoung-Lim** [comment]
@stmoon Sorry, on the instructions side I think you can put it wherever you think fits best!

**Pull request merged**
