### PR TITLE
submodule optical flow

### PR DESCRIPTION
**Pull request by ChristophTobler**
These are the changes to include the new optical flow repo in sitl gazebo. There are two flow implementations: klt_feature_tracker/opencv and px4flow.
I have also changed the camera image format to avoid unnecessary format changes.
The goal is to use this flow repo where ever flow calculations are needed and to avoid duplicated code. Also other implementations can (and hopefully will) be added in the future.

### CODE REVIEW

**Comment by ChristophTobler** [comment]
@LorenzMeier or @jgoppert  can you review these changes?

**Comment by LorenzMeier** [comment]
The diff looks good - what kind of testing was performed to validate that the result / performance is still working?

**Comment by ChristophTobler** [comment]
I tested it with the lpe and the behavior is still the same as with the old implementation (see https://github.com/PX4/Firmware/issues/5985). I'm currently trying to get it to run with the ekf2 but there are still some issues. But they're the same for the old flow implementation. I'm in contact with @priseborough  about that.

**Comment by ChristophTobler** [comment]
@LorenzMeier With the INAV the flow simulation still works great. Results tend to be a bit better for the OpenCV flow implementation.

**Comment by LorenzMeier** [comment]
Now we need a PR against PX4/Firmware and need to add this to the CI tests (if not already done) so that we get test coverage.

**Pull request merged**
