### PR TITLE
Set initial magnetometer bias to zero

### PR DESCRIPTION
**Pull request by EliaTarasov**
This pr fixes random magnetometer failures due to random bias init.

### CODE REVIEW

**Comment by TSC21** [comment]
@EliaTarasov can you please provide logs of testing this against some of the CI tests on PXa4 Firmware? Also, are you able to run thos correctly under a catkin_ws when PX4 gets buils with catkin build?

**Comment by julianoes** [comment]
I think it's scary that we can have cases like this with uninitialized variables. To me everything should be initialized with sane defaults and otherwise we should get compiler warnings.

**Comment by TSC21** [comment]
@julianoes we need a CI pipeline with some sanity check or we set that by default on CMake.

**Comment by EliaTarasov** [comment]
@TSC21 
> can you please provide logs of testing this against some of the CI tests on PXa4 Firmware? Also, are you able to run thos correctly under a catkin_ws when PX4 gets buils with catkin build?

Yes i can do on the next week. I won't be on my PC until then.

@julianoes 
>I think it's scary that we can have cases like this with uninitialized variables. To me everything should be initialized with sane defaults and otherwise we should get compiler warnings.

Yes for sure. But this is done for [consistency](https://github.com/PX4/sitl_gazebo/blob/master/src/gazebo_imu_plugin.cpp#L183).

**Comment by julianoes** [comment]
Right, yes I meant this as an overall comment about all these plugins, not just this new one.

**Comment by julianoes** [comment]
I'm testing it right now.

**Comment by julianoes** [comment]
I could not reproduce the issue locally with this change, I'll merge it and bring it into PX4. Hopefully it will fix the CI issues.

**Review by julianoes — APPROVED** [review]

**Pull request merged**
