### PR TITLE
Fix typo in OpticalFlow package

### PR DESCRIPTION
**Pull request by vTechSavyy**

### CODE REVIEW

**Comment by LorenzMeier** [comment]
@ChristophTobler Please review.

**Comment by ChristophTobler** [comment]
@JesusSaves747 This is no typo. ```calcFlow``` expects a ```const cv::Mat &img_current``` at the current version. 
Your PR produces the error: ```no matching function for call to ‘OpticalFlowOpenCV::calcFlow(uchar*&, uint32_t&, int&, float&, float&)’```

Maybe you got confused because OpticalFlow master does not use ```cv::Mat``` anymore. I think this should be integrated by @gbmhunter in https://github.com/PX4/Firmware/pull/6380

**Comment by gbmhunter** [comment]
@ChristophTobler yes you are correct. The `master` branch of OpticalFlow was changed to use a `uchar*&`, but PX4 hasn't been updated to use this yet (still uses `cv::Mat`). The pull request does bring PX4 up-to-date.

**Comment by ChristophTobler** [comment]
@gbmhunter But you can not change this unless you update the submodule as well. I though we're waiting for your monster merge :)

**Comment by gbmhunter** [comment]
Yeah.... :-O It is coming! Just working through requested changes to the rotors_simulator pull-request by the ASL team atm, hopefully this is all done very, very soon :-)

**Pull request closed without merging**
