### PR TITLE
Fix macOS CI

### PR DESCRIPTION
**Pull request by julianoes**
This fixes the warning seen mostly on macOS:

```
warning: expression result unused [-Wunused-value]
for( e_model; e_model; e_model=e_model->NextSiblingElement("model")
     ^~~~~~~
```

### CODE REVIEW

**Review by TSC21 — APPROVED** [review]

**Comment by LorenzMeier** [comment]
Great!

**Comment by LorenzMeier** [comment]
@julianoes Build failed

**Comment by julianoes** [comment]
@LorenzMeier right.

- Both catkin_builds fail because MAVROS is outdated and doesn't include a message that has been added or changed.
- macOS Gazebo8 is built instead of poured from the bottle and travis times out.
- macOS Gazebo9 is built but fails to link against some boost libs, that's something to look at:
```
Undefined symbols for architecture x86_64:
  "boost::timer::cpu_timer::stop()", referenced from:
```

**Comment by julianoes** [comment]
The linking error is still there although I can't reproduce it locally yet.

**Comment by julianoes** [comment]
Btw. these CI errors existed before but I'm still trying to get hold of them in this PR while I'm at it.

**Comment by julianoes** [comment]
@TSC21 still ok with this?

**Comment by TSC21** [comment]
Yep. Sure. The ROS fix is a matter of bumping the container tags on the travis file. Can you do that please?

**Comment by julianoes** [comment]
@TSC21 thanks let me try that.

**Pull request merged**
