### PR TITLE
Switch to use pkg-config to get gstreamer args.

### PR DESCRIPTION
**Pull request by tfoote**
This stopped working in my tests on 18.04. The INCLUDE_DIRS was not set
And pkg-config appears to be the recommended approach: http://gstreamer-devel.966125.n4.nabble.com/cmake-find-package-what-is-the-proper-gstreamer-package-name-td4680254.html

Since this is switching to use the recommended approach for finding gstreamer I'd suggest that this supplant #326

### CODE REVIEW

**Comment by tfoote** [comment]
@dayjaby can you try this out on your system?

**Comment by LorenzMeier** [comment]
This might be broken on Mac OS. There is pkg-config available but it doesn't actually find gstreamer as framework.

**Comment by TSC21** [comment]
@tfoote @LorenzMeier I can actually see this happening on Travis CI on master: https://travis-ci.org/PX4/sitl_gazebo/jobs/573253980. I will rebase this and try it out.

**Comment by TSC21** [comment]
Superseded by https://github.com/PX4/sitl_gazebo/pull/341.

**Pull request closed without merging**
