### PR TITLE
Update sitl_gazebo to allow use in a catkin workspace

### PR DESCRIPTION
**Pull request by tfoote**
There are two main components
The first is to add environment hooks to support referencing plugins and models from other packages.

The second is to update sitl_gazebo to use the recently merged changes in https://github.com/PX4/OpticalFlow/pull/6 in the OpticalFlow module to fix the compile in isolation.

### CODE REVIEW

**Review by TSC21 — APPROVED** [review]
LGTM. Thanks

**Comment by TSC21** [comment]
Travis is not liking the hook.

**Comment by tfoote** [comment]
I added a guard to avoid the catkin method if not building in an catkin environment.

**Comment by TSC21** [comment]
We definitely need a second CI build for the ROS side to assert over this. Thanks @tfoote

**Pull request merged**
