### PR TITLE
Visualize control surfaces for model plane

### PR DESCRIPTION
**Pull request by Jaeyoung-Lim**
This PR visualizes the control surfaces of the plane and moves the aileron joints to the correct location.

Previously the plane control surfaces were not visualzied and it was hard to do sanity checks on the control surfaces. This seems to be the reason why the aileron joint was in a wierd position under the wing until now.(This does not affect the performance of the flight)

The joint location and visualzation is compared with the following two images
Before PR:
Screenshot from 2019-12-24 22-40-59
After PR:
Screenshot from 2019-12-24 22-28-09

### CODE REVIEW

**Comment by LorenzMeier** [comment]
Nice!

**Comment by ryanjAA** [comment]
This will be a good!

**Comment by Jaeyoung-Lim** [comment]
@LorenzMeier @ryanjAA Thanks!

**Comment by Jaeyoung-Lim** [comment]
@LorenzMeier @TSC21 Can we this merged please?

**Comment by LorenzMeier** [comment]
Have you seen the failing checks?

**Comment by LorenzMeier** [comment]
It’s in the video widget, so unrelated.

**Review by LorenzMeier — APPROVED** [review]

**Comment by Jaeyoung-Lim** [comment]
@LorenzMeier Thanks!

**Pull request merged**
