### PR TITLE
cmake use gold linker if available

### PR DESCRIPTION
**Pull request by dagar**

### CODE REVIEW

**Review by TSC21 — APPROVED** [review]

**Comment by TSC21** [comment]
@dagar CI is complaining:
```bash
Errors     << mavlink_sitl_gazebo:make /home/user/catkin_ws/logs/mavlink_sitl_gazebo/build.make.000.log
/usr/lib/x86_64-linux-gnu/libopencv_freetype.so.3.2.0: error: undefined reference to 'hb_buffer_create'
/usr/lib/x86_64-linux-gnu/libopencv_freetype.so.3.2.0: error: undefined reference to 'FT_Done_Face'
/usr/lib/x86_64-linux-gnu/libopencv_freetype.so.3.2.0: error: undefined reference to 'FT_Render_Glyph'
/usr/lib/x86_64-linux-gnu/libopencv_freetype.so.3.2.0: error: undefined reference to 'FT_New_Face'
/usr/lib/x86_64-linux-gnu/libopencv_freetype.so.3.2.0: error: undefined reference to 'hb_buffer_get_glyph_infos'
/usr/lib/x86_64-linux-gnu/libopencv_freetype.so.3.2.0: error: undefined reference to 'hb_buffer_add_utf8'
/usr/lib/x86_64-linux-gnu/libopencv_freetype.so.3.2.0: error: undefined reference to 'FT_Done_FreeType'
/usr/lib/x86_64-linux-gnu/libopencv_freetype.so.3.2.0: error: undefined reference to 'hb_font_destroy'
/usr/lib/x86_64-linux-gnu/libopencv_freetype.so.3.2.0: error: undefined reference to 'FT_Outline_Translate'
/usr/lib/x86_64-linux-gnu/libopencv_freetype.so.3.2.0: error: undefined reference to 'FT_Outline_Decompose'
/usr/lib/x86_64-linux-gnu/libopencv_freetype.so.3.2.0: error: undefined reference to 'FT_Init_FreeType'
/usr/lib/x86_64-linux-gnu/libopencv_freetype.so.3.2.0: error: undefined reference to 'hb_buffer_destroy'
/usr/lib/x86_64-linux-gnu/libopencv_freetype.so.3.2.0: error: undefined reference to 'FT_Outline_Transform'
/usr/lib/x86_64-linux-gnu/libopencv_freetype.so.3.2.0: error: undefined reference to 'hb_ft_font_create'
/usr/lib/x86_64-linux-gnu/libopencv_freetype.so.3.2.0: error: undefined reference to 'hb_buffer_guess_segment_properties'
/usr/lib/x86_64-linux-gnu/libopencv_freetype.so.3.2.0: error: undefined reference to 'FT_Load_Glyph'
/usr/lib/x86_64-linux-gnu/libopencv_freetype.so.3.2.0: error: undefined reference to 'hb_shape'
/usr/lib/x86_64-linux-gnu/libopencv_freetype.so.3.2.0: error: undefined reference to 'FT_Set_Pixel_Sizes'
```

May be related: https://github.com/opencv/opencv_contrib/issues/1175

**Comment by dagar** [comment]
Looks like a real failure.

**Comment by TSC21** [comment]
It is. Can't really tell a straight solution for now. Maybe using OpenCV installed from source would help.

**Comment by TSC21** [comment]
@dagar should we wrap a workaround to this?

**Comment by dagar** [comment]
I haven't had a chance to dig into it and find the core problem. We could do a quick comparison on one of working platforms to see if this is worth the effort first.

**Pull request closed without merging**
