### PR TITLE
Run on separate sitl configs with firmware

### PR DESCRIPTION
**Pull request by Jaeyoung-Lim**
This enables running SITL tests on a different config than the firmware.

I also noticed that the `make px4_sitl_default gazebo` needs to be run before changing the submodule branch in order to be on the correct branch. Therefore, this PR includes a workaround of building twice
(@bkueng Any idea why this is happening?)

Models running tests
- `iris`
- `standard_vtol`

Models with intermittent failures
- `tailsitter`

Models that have been tested, but that do not pass the test (therefore not added)
- `px4vision`, `solo`, `typhoon_h480`, `tiltrotor`

### CODE REVIEW

**Comment by Jaeyoung-Lim** [comment]
@dagar @julianoes I am not sure if the SITL failures here are related to the intermittent failures upstream. Could you shed any light if I need to fix this in the submodule layer?

**Comment by Jaeyoung-Lim** [comment]
Fix for the comment above was to have `GIT_SUBMODULES_ARE_EVIL: 1` 

Thanks @dagar for the pointers!

**Comment by TSC21** [comment]
Tests are failing

**Comment by Jaeyoung-Lim** [comment]
@TSC21 Yes, but not because the PR is incorrect, but this better reflects reality!

**Comment by Jaeyoung-Lim** [comment]
@dagar This seems to be much more reliable than before

@TSC21 I reverted #567 since it was making the tests quite unstable.

**Review by jkflying — APPROVED** [review]

**Pull request merged**
