### PR TITLE
initial travis-ci configuration

### PR DESCRIPTION
**Pull request by dagar**
@ndepal @TSC21 FYI

### CODE REVIEW

**Comment by dagar** [comment]
Should we add mavlink directly or px4?

**Comment by TSC21** [comment]
PX4 gives us more flexibility to run some unittests. We will also require ROS for the HIL support but I guess we can split that for different builds by running docker containers

**Comment by TSC21** [comment]
Ok looks like the problem is actually on the dockerfile (https://hub.docker.com/r/px4io/px4-dev-simulation/~/dockerfile/):
```
&& git clone git://github.com/mavlink/mavlink.git && ln -s $PWD/mavlink/message_definitions ../ \`
&& pip install . && cd .. && rm -rf pymavlink && rm -rf message_definitions \
```
it deletes the `mavlink` dir (with the `pymavlink` dir) after installing the message definitions.

@dagar can we update the container so it does not delete the `mavlink` folder?

**Review by LorenzMeier — COMMENTED** [review]
ROS distros can have conflicting MAVLink versions and SITL is linked to Firmware, not MAVROS. Could you please set the ROS search path to lower priority by putting it at the end of the search path? It should go for the local Firmware version.

**Comment by TSC21** [comment]
> ROS distros can have conflicting MAVLink versions and SITL is linked to Firmware, not MAVROS. Could you please set the ROS search path to lower priority by putting it at the end of the search path? It should go for the local Firmware version.

I'm trying to make it the more general possible. The issue is: we should then have the mavlink source on the docker containers, cause it seems to be having trouble on getting the `mavlink_types.h` somehow.

**Comment by TSC21** [comment]
I will look for a better option on the container side.

**Comment by LorenzMeier** [comment]
This repo should use the generated MAVLink files: https://github.com/mavlink/c_library_v2 - not generate them itself.

**Comment by LorenzMeier** [comment]
I've updated this on master.

**Comment by LorenzMeier** [comment]
And just rebased this. Let's see if this builds.

**Comment by TSC21** [comment]
@LorenzMeier the issue here is that the container structure does not have the mavlink headers available atm. So I think it would be a good idea to clone https://github.com/mavlink/c_library_v2 on the `simulation` container and add it to `/user/local/` (for example), and that way the build is not directly dependent on having the PX4 Firmware repository being built on the container also. If you agree, I will do a PR with that same change.

**Comment by TSC21** [comment]
Ok I think the latest containers states are going to fix this. @dagar would you mind tagging the latest containers?

**Comment by TSC21** [comment]
@dagar seems like we have a go now

**Review by TSC21 — APPROVED** [review]

**Comment by dagar** [comment]
Nice work Nuno!

**Pull request merged**
