### PR TITLE
remove old & unused models: if750a, iris_ctrlalloc, solo, typhoon_h480_ctrlalloc

### PR DESCRIPTION
**Pull request by bkueng**
From https://github.com/PX4/PX4-Autopilot/pull/19990

### CODE REVIEW

**Review by Jaeyoung-Lim — COMMENTED** [review]
Thanks! 

For the if750a, that is currently the only model where you can test a parachute on flight termination. Do we want to delegate this to another model?

**Comment by bkueng** [comment]
Yes I would

**Comment by Jaeyoung-Lim** [comment]
@bkueng Any suggestions? Not sure if we have a good candidate that is based on a real vehicle

**Comment by bkueng** [comment]
typhoon maybe? Otherwise we can leave it out for now.

**Review by Jaeyoung-Lim — APPROVED** [review]

**Pull request merged**
