### PR TITLE
Improvements

### PR DESCRIPTION
**Pull request by nicolaerosia**
Hello,

This is a PR which contains some other commits on top of the other two PRs.

### CODE REVIEW

**Comment by LorenzMeier** [comment]
Thanks!

**Comment by LorenzMeier** [comment]
What OS did you test on?

**Comment by nicolaerosia** [comment]
I'm testing on Fedora 23.
I have compiled everything from source.
I've used the latest Gazebo available @ bitbucket

**Comment by stmoon** [comment]
great!!

**Comment by nicolaerosia** [comment]
Any comments?

**Comment by LorenzMeier** [comment]
Closing in favour of #19.

**Pull request closed without merging**
