### PR TITLE
Add Quadtailsitter model based on the swan K1

### PR DESCRIPTION
**Pull request by Jaeyoung-Lim**
**Problem Description**
This PR adds a Quadtailsitters VTOL based on the [HEQ Swan K1](https://store.hequavtech.com/product/Swan-K1-PRO-Base-Platform)

These VTOLs have no control surfaces were not available and therefore use the differential thrust to control the vehicle. 

**Testing**
The model can be tested using the PR: https://github.com/PX4/PX4-Autopilot/pull/20558

- Video: https://youtu.be/EDb019z56cA
- Log: https://review.px4.io/plot_app?log=c4430cb6-1ed8-4bcc-b9ff-ae3d1196a501

Thanks Holybro for providing the 3D model for the vehicle! and @julianoes making it flyable!

### CODE REVIEW

**Comment by hamishwillee** [comment]
We got docs for this, and a frame build?

**Comment by Jaeyoung-Lim** [comment]
@hamishwillee I will add the docs once the main is merged, but no frame builds since it never flew on real hardware

**Comment by hamishwillee** [comment]
Great thanks. I wonder if we should/could have some sort of automated build of the frames info for simulator in the same way as we do for "real" airframes?

**Comment by Jaeyoung-Lim** [comment]
@hamishwillee That would be nice. Eould you be able to shed some light on how it is done for real airframes?

**Comment by hamishwillee** [comment]
@Jaeyoung-Lim Yes.
It's parsing over the airframe files - done in make using these files: https://github.com/PX4/PX4-Autopilot/blob/main/Tools/px4airframes/markdownout.py

So `make airframe_metadata`. I wouldn't be surprised if the modification for simulations was minimal.

@bkueng is the expert.

**Pull request merged**
