### PR TITLE
Added new jinja based models.

### PR DESCRIPTION
**Pull request by jgoppert**
Adds jinja generator and models for matrice 100, px4flow, sf10a etc.

### CODE REVIEW

**Comment by TSC21** [comment]
@jgoppert are we on a condition of documenting this in order that one that wants to create is own model is able to do it using jinja generator? This could also integrate https://github.com/PX4/sitl_gazebo/issues/110

**Comment by LorenzMeier** [comment]
@jgoppert Happy to bring these in if you could rebase.

**Comment by TSC21** [comment]
@LorenzMeier this is now rebased. Some considerations though:
1. The jinja generated models won't go through the schema validator. That means we cannot currently validate any `.sdf.jinja` model that uses jinja generator in order to generate `.sdf` files, unless we update the schemas (that would be a work that could include validate schemas that use `xmlns:xacro`).
2. Documentation: (@hamishwillee FYI):
- Should be documented how to create jinja description files that the `jinja_gen` reads and parses to `.sdf`;
- Comparison between jinja based vs xacro based generation (why? performance? easy of use?)
- Add the new airframe (the DJI Matrice 100) to the devguide - https://dev.px4.io/en/simulation/gazebo.html

**Comment by jgoppert** [comment]
The typical way that OSRF does this is they include the generated files in the repo, then you can validate that.

**Comment by dagar** [comment]
Apologies if I'm out of the loop, but why can't you have CI generate and validate?

**Comment by jgoppert** [comment]
@tsc21 jinja is just more powerful then xacro or erb, we weren't sure if this was the right way to go, but in the end however you generate the sdf doesn't matter as long as it is easy to use/maintain, so that is the real question with this PR, do you guys like this approach? @dagar, that is true, we could validate the generated files.

**Comment by TSC21** [comment]
Yeah I was considering the validation a priori and not after generation. But yes, we can validate after compiling on CI, it's just a matter of reversing the order. Will do that today.

**Comment by TSC21** [comment]
@jgoppert being simple, powerful and ease to maintain depends on having good documentation. And that's why I said above this should be documented properly (why; how to use). I like the method but one should be able to creates his own jinja-based files the same way.

**Comment by TSC21** [comment]
Ok I update this PR so the schemas can be validated after build and found that some of the XSD are not up to date or don't support some of SDF structures applied on the models added in this PR. So, I added those for an exclusion list on the validation script, while I don't update/replace the XSD forthe schema validation that supports the different elements being added. So, I think this is good to go now.
@LorenzMeier feel free to review and merge.

**Comment by dagar** [comment]
Could you briefly explain the advantages over xacro?

**Comment by jgoppert** [comment]
@dagar jinja has for loops, while loops, can do stuff like do a for loop over multirotor arms like I did here, also the docs for jinja are better and it is more well known http://jinja.pocoo.org/docs/2.10/

**Comment by dagar** [comment]
Any concerns with this hindering possible collaboration with other projects?

The other thing that immediately stands out to me is that xacro is specifically an XML macro language which means you could perform other transformations or validate it as is.

**Comment by jgoppert** [comment]
@dagar a lot of the time now I find myself just using a python script + jinja to generate things like forests, warehouse environments, So in the end the source is just a python script, and then that generates the sdf, which you can validate, but there is no way to make such a thing using xacro

**Comment by TSC21** [comment]
@jgoppert I find it particulary interesting, but I think this would actually make much more sense and much more useful to users and developers if this could be actually documented on the Devguide. Do you have the bandwidth to add some docs there explaining the advantages and adding a use case of how people can actually take advantage of jinja for the Gazebo sim? That would be awesome! (**Note:** I know that writing is always the hardest part eheh)

**Comment by dagar** [comment]
> @dagar a lot of the time now I find myself just using a python script + jinja to generate things like forests, warehouse environments, So in the end the source is just a python script, and then that generates the sdf, which you can validate, but there is no way to make such a thing using xacro

Yes that makes sense, I was just hoping for a solution that aligns with the ROS community.

In business applications when you want to output xml typically you generate the entire thing and don't directly deal with xml tags or templates. Possibly something to consider for the future.

**Comment by TSC21** [comment]
Is there something missing on this PR? Maybe we can merge and then document it? @LorenzMeier

**Review by LorenzMeier — APPROVED** [review]

**Pull request merged**
