### PR TITLE
Added Skywalker X8 to sitl_gazebo

### PR DESCRIPTION
**Pull request by iwishiwasaneagle**
The `standard_vtol` is the Skywalker X8 with some additional components. This pull is a purely fixed-wing version of that, with some adjusted numbers of mass and inertia to compensate for the lack of 4 motors and the associated frame. 

Tested extensively in SITL during development with MAVSDK.

Sources
 - [Estimation of the lateral aerodynamic coefficients for skywalker x8 flying wing from real flight-test data](https://www.researchgate.net/publication/325043884_Estimation_of_the_lateral_aerodynamic_coefficients_for_skywalker_x8_flying_wing_from_real_flight-test_data)  
- [Aerodynamic  modeling  of  the  Skywalker  X8  Fixed-Wing  Unmanned Aerial  Vehicle](http://folk.ntnu.no/richahan/Publications/2018_Gryte%20et%20al_ICUAS.pdf)

### CODE REVIEW

**Review by Jaeyoung-Lim — COMMENTED** [review]
Could you explain what value this model gives / or what we can test using this model that we weren't able to test before?

**Comment by iwishiwasaneagle** [comment]
> Could you explain what value this model gives / or what we can test using this model that we weren't able to test before?

Universities love this model, and they also love making students do simulations. Having this model available for them on the official `PX4/sitl_gazebo` is convenient. 

As well as this, there is currently only 2 other fixed-wing model that I'm aware of - `plane` and `zephyr`. Whereas multicopters have many more with many variants: `iris`, `3dr solo`, `if750a`, `typhoon h480` .

**Comment by Jaeyoung-Lim** [comment]
@iwishiwasaneagle I am a bit hesitant on bringing more models without added value in testing, since it contributes to increase the size of the firmware repo.

Also, in the model I see that the vehicle is not a flying wing, but a standard plane (it has a elevator). Would you be able to make this plane to fly as a delta wing? That would definitely be an added value to the plane fleet

**Comment by Jaeyoung-Lim** [comment]
@iwishiwasaneagle Any updates?

**Comment by iwishiwasaneagle** [comment]
> @iwishiwasaneagle Any updates?

@Jaeyoung-Lim hi sorry I've been busy with my MEng project but intend to finish this when I find some time. I got stuck on getting the mixers to properly work.

**Comment by iwishiwasaneagle** [comment]
I don't have the time to work on this sadly so closing the PR for now.

**Pull request closed without merging**
