### PR TITLE
Update camera settings

### PR DESCRIPTION
**Pull request by dogmaphobic**

### CODE REVIEW

**Comment by TSC21** [comment]
@dogmaphobic this won't probably build on the Ubuntu Travis jobs as is now since we need the containers updated and also a ROS Mavlink release.

**Comment by dogmaphobic** [comment]
> @dogmaphobic this won't probably build on the Ubuntu Travis jobs as is now since we need the containers updated and also a ROS Mavlink release.

I have no idea what that even means.

**Comment by TSC21** [comment]
It means:
1. In the `catkin` builds, which depend on the ROS environment, and so, on the [ROS Mavlink package](https://github.com/mavlink/mavlink-gbp-release), it will fail to build, since https://github.com/mavlink/mavlink/pull/1017 was merged yesterday and the ROS Mavlink releases are made once a month;
2. In the raw CMake build it will also fail because the [px4-dev-simulation](https://hub.docker.com/r/px4io/px4-dev-simulation/) Docker container is not up to date built (I already triggered the build though) so to bring the new Mavlink definitions in the `RUN git clone --depth 1 https://github.com/mavlink/c_library_v2.git /usr/local/include/mavlink/v2.0 && rm -rf /usr/local/include/mavlink/v2.0/.git` step.

So we need to wait that the CI system gets updated first before we merge this or we will break it.

**Comment by TSC21** [comment]
Given this does block a `sitl_gazebo` upgrade on PX4 upstream master, we will probably need to force breaking the CI. @LorenzMeier what do you think?

**Review by TSC21 — APPROVED** [review]

**Comment by dogmaphobic** [comment]
Catch 22. Can't update MAVLink because it breaks CI while CI is broken because of non updated MAVLink.

**Comment by TSC21** [comment]
> Catch 22. Can't update MAVLink because it breaks CI while CI is broken because of non updated MAVLink.

Something like that :P Though it's two separate Mavlink releases which are out of sync. That's the issue

**Comment by dagar** [comment]
Let me see if I can figure out the CI dance.

**Comment by TSC21** [comment]
@dagar the ROS builds expect a ROS Mavlink package up to date. Which does only happen when mavlink-gbp-release is released and the deb package is made available.

**Comment by TSC21** [comment]
I think we can merge it as is so to not delay the development. Currently this is a container/ROS package version rather than a fail on the code.

**Comment by dagar** [comment]
I think we can tolerate temporary sitl_gazebo breakage in master to get this sorted out. Merging.

**Review by dagar — APPROVED** [review]

**Pull request merged**
