### PR TITLE
WIP: Always start in follow camera mode

### PR DESCRIPTION
**Pull request by LorenzMeier**
Not yet finished, needs to be embedded with all the generation.

@Jaeyoung-Lim Could you help with the generation? This improves the UX a lot.

https://user-images.githubusercontent.com/1208119/103456229-74308480-4cf4-11eb-95a2-739b07405e68.mp4

### CODE REVIEW

**Review by Jaeyoung-Lim — COMMENTED** [review]
@LorenzMeier Thanks, I agree this improves the UX alot. However one problem I see with this PR is that multivehicle sim will break with this PR, since there is no model named without indexes.

**Comment by LorenzMeier** [comment]
Have you seen my note about this needing integration with the generators? Could you help with that?

**Comment by Jaeyoung-Lim** [comment]
@LorenzMeier Yes, I will look into this - for context, I am trying to think of a better way than generate world files through jinja templates

**Comment by Jaeyoung-Lim** [comment]
Sharing what I have been doing regarding looking into this topic
- I agree that this definitely enhances the user experience, but it is not trivial how we can add this.
- Currently world files are not generated, and this was on purpose. Models get generated at build time with different configs, and get spawned into a static world. (e.g. worlds do not generated with model specific configurations)
- To workaround the issue above, I created a `user_camera_plugin` which controls the user camera in order to "follow" the vehicle: https://github.com/PX4/PX4-SITL_gazebo/tree/pr-user-camera
To test, you can simply run the following command. However, the user camera control interface which gazebo exposes through a gazebo transport seems quite unstable with intermittent failures and failing to keep up with high update rates. 
```
make px4_sitl gazebo
```


**Possible Next steps**
- Go down the messy route: Use a build-time generated world file just when using make targets, (which trigger on build) and leave the previous worldfile behavior as is for other usecases (ROS/Multivehicles)

Update: Found a way to deal with this use case using a gui-plugin inside gazebo client.

**Comment by Jaeyoung-Lim** [comment]
@LorenzMeier I would like to replace this PR with https://github.com/PX4/PX4-SITL_gazebo/pull/691

If this is okay, may I close this PR?

**Pull request closed without merging**
