### PR TITLE
Detatch model from worlds and cleanup

### PR DESCRIPTION
**Pull request by Jaeyoung-Lim**
Most of the worlds in this repo are used only for spawning the model, which is not necessary. For example, `iris_opt_flow`, `iris_rtps`, `iris` are exactly the same worlds with different models inside the world. 

I would argue that only worlds that need to be specific for a model (e.g. hippocampus / typhoon_h480 ) should have a world file named after the model. 

This PR
- Removes the models from the world so that the model spawning can be done separately as in https://github.com/PX4/Firmware/pull/14166
- Removes unnecessary worlds that are mostly redundant with `empty.world`

### CODE REVIEW

**Comment by Jaeyoung-Lim** [comment]
This is bit wierd, I have no conflicts locally

**Comment by TSC21** [comment]
@Jaeyoung-Lim are we good to go on this?

**Comment by Jaeyoung-Lim** [comment]
@TSC21 
@hamishwillee Pointed out that the make targets are not consistent with the docs. I will make it ready before tomorrow morning

**Comment by TSC21** [comment]
> @TSC21
> @hamishwillee Pointed out that the make targets are not consistent with the docs. I will make it ready before tomorrow morning

Sounds good!

**Comment by hamishwillee** [comment]
Great. Once this is in I will tidy up the docs.

**Review by bkueng — APPROVED** [review]

**Pull request merged**
