### PR TITLE
Fixing the links and joints names in typhoon model

### PR DESCRIPTION
**Pull request by ayhamalharbat**
This fixes the inconsistent numbering of the links and joints to make it match the numbers of the motors in the [px4's hex x airframe](https://docs.px4.io/main/en/airframes/airframe_reference.html#hexarotor-x).

### CODE REVIEW

**Comment by Jaeyoung-Lim** [comment]
@ayhamalharbat This seems to have the peach model also included. Was this intentional?

**Comment by ayhamalharbat** [comment]
No that is a mistake. Feel free to remove them. Thanks!

**Comment by Jaeyoung-Lim** [comment]
@ayhamalharbat Since this is on your fork, I will not be able to remove them.

If you don't plan to continue the PR, please close the PR

**Comment by Jaeyoung-Lim** [comment]
Closing as there was no response

**Comment by ayhamalharbat** [comment]
Thanks @Jaeyoung-Lim . I was going to close it and open a new one with correct commits.

**Pull request closed without merging**
