### PR TITLE
Add vtol foot model

### PR DESCRIPTION
**Pull request by TigerWuu**
I made a vtol supporting frame to avoid a contact between standard_vtol and the ground.

Once we want to add sensor such as gimbal or the other rangefinders, the contact between the standard_vtol and the ground may cause an unpleasant result. That;s the context why I want to build a supporting frame to keep the standard_vtol and the ground a distance.

### CODE REVIEW

**Review by Jaeyoung-Lim — CHANGES_REQUESTED** [review]
Could you already add the gimbal/sensor that you mention that is interesting to this model?

This model might be useful when additional payload is added, but not really useful without one

Also, could you elaborate on why we actually need a foot in comparison with simply a larger collision box that gives clearance for the gimbal?

**Comment by TigerWuu** [comment]
Thanks for your reply.

First, I have already added the gimbal to my vtol that showed below

328953715_1299637240894141_2685208399094678530_n

329327372_1480557949020631_357452789186945431_n

It is not difficult to imagine that once we remove the foot, the gimbal will directly touch the ground. I think it doesn't make sense in the real world.

Secondly, I think the foot should be the essential element in any kind of plane. It is also match the reality in the real world. Take the original standard_tol for an example, the space (red box) between the belly and the ground won't exist in the real world.

vtol

Thirdly,  if we add a large box under the vtol, it will block the camera in the model of standard_vtol_downward_camera. I want to build a general solution that can be applied by the people who want to add sensor to the standard_vtol.

Thanks.

**Comment by TigerWuu** [comment]
I update the author information and the .stl location.
Please review it. Thanks.

**Comment by hamishwillee** [comment]
When this is done, would be good to add to docs in:
- The list here: http://docs.px4.io/main/en/sim_gazebo_classic/#running-the-simulation
- The page here: http://docs.px4.io/main/en/sim_gazebo_classic/gazebo_vehicles.html

If this is useful for something in particular, like video, gimbals etc, there are sections in the top level doc http://docs.px4.io/main/en/sim_gazebo_classic/#video-streaming where you can talk about them, so that others know what frames allow testing what features.

**Comment by Jaeyoung-Lim** [comment]
> Once we want to add sensor such as gimbal or the other rangefinders, the contact between the standard_vtol and the ground may cause an unpleasant result. That;s the context why I want to build a supporting frame to keep the standard_vtol and the ground a distance.

So, as far as I understand, this is a cosmetic change and not really related to the functionality correct?

**Review by Jaeyoung-Lim — CHANGES_REQUESTED** [review]
> Once we want to add sensor such as gimbal or the other rangefinders, the contact between the standard_vtol and the ground may cause an unpleasant result. That;s the context why I want to build a supporting frame to keep the standard_vtol and the ground a distance.

So, as far as I understand, this is a cosmetic change and not really related to the functionality correct?

The PR committed does not have a functional gimbal mounted on the model. If the change is proposed to enhance the cosmetics of the model, I would prefer to have a working gimbal with the model

**Comment by Jaeyoung-Lim** [comment]
@TigerWuu Closing as stale, please reopen if you are interested in continuing

**Pull request closed without merging**
