### PR TITLE
Gazebo 7 build fixes

### PR DESCRIPTION
**Pull request by nicolaerosia**
Hello,

I'm using the SITL with Gazebo 7.
These commits fix the compilation errors and warnings against Gazebo 7.

### CODE REVIEW

**Comment by nicolaerosia** [comment]
Any comments?

**Comment by LorenzMeier** [comment]
Did you get a chance to look into the ifdefs for version 6 and 7?

**Comment by nicolaerosia** [comment]
I forgot about this.
I'll do it today. Thanks for reminding me

**Comment by nicolaerosia** [comment]
Done. Please test.

**Comment by LorenzMeier** [comment]
Nice, works, merging!

**Comment by LorenzMeier** [comment]
Sorry for the delay with this - we will be more timely from now on, you sent it at a time where I was travelling a lot.

**Pull request closed without merging**
