### PR TITLE
change default update rate to 200 Hz

### PR DESCRIPTION
**Pull request by dagar**
- this goes along with the change PX4 side https://github.com/PX4/Firmware/pull/14759

### CODE REVIEW

**Review by julianoes — COMMENTED** [review]
What I'm confused about is where the 500 Hz update rate went to because VTOL models did not fly well at 250 Hz simulation rate, so at 200 Hz it will be even worse. (I'm not talking about the rate at which the communication happens over MAVLink but the internal Gazebo rate.)

Edit:
Ok @Jaeyoung-Lim helped me understand this. It's presumably fixed with https://github.com/PX4/sitl_gazebo/pull/471.

**Review by Jaeyoung-Lim — COMMENTED** [review]
@dagar @julianoes What is still not solved is the landing gear oscillating depending on the update rate. This will potentially change how the typhoon_h480 oscillates

**Comment by dagar** [comment]
Tested in https://github.com/PX4/Firmware/pull/14759.


Iris looks fine, but the typhoon h480 landing gear are shaking at 200 Hz.

**Review by julianoes — APPROVED** [review]

**Comment by LorenzMeier** [comment]
This is stale, closing.

**Pull request closed without merging**
