### PR TITLE
vision: by default, do not send ODOMETRY Mavlink msgs

### PR DESCRIPTION
**Pull request by TSC21**
@mhkabir please have a go. @EliaTarasov please check if this agrees with your experiments.

### CODE REVIEW

**Comment by TSC21** [comment]
This can be changed back again when https://github.com/PX4/Firmware/pull/9301 gets in.

**Comment by mhkabir** [comment]
Disabling odometry sending in the interface seems to work. Didn't test this PR yet.

**Comment by EliaTarasov** [comment]
It's ok for me. I still use VISION_POSE for tests.

**Comment by TSC21** [comment]
Can I get an approval for merging?

**Review by LorenzMeier — APPROVED** [review]

**Pull request merged**
