### PR TITLE
mavlink: send mavlink_hil_state_quaternion_t ground truth message

### PR DESCRIPTION
**Pull request by bkueng**
I thought since jmavsim has ground truth, it would be cool if gazebo had it as well.

fyi @kd0aij

### CODE REVIEW

**Comment by kd0aij** [comment]
@bkueng Looks good to me; I assume you're converting between ENU and NED there. We should double-check whether I got the frame conversions right for jMAVSim. I can't find any explicit coordinate frame definition in the Java code, but there are comments that indicate NED is used for wind, magnetic and position vectors.

**Comment by bkueng** [comment]
I can't say I'm fluent with quaternions, so I just used the transformations that give a matching result (from gazebo using ENU). That's based on the assumption that yours is correct.
Just looked through the code and found this: https://github.com/PX4/Firmware/blob/master/src/examples/ekf_att_pos_estimator/ekf_att_pos_estimator_main.cpp#L842
It suggests that roll & pitch should be swapped in simulator_mavlink.cpp.

**Comment by bkueng** [comment]
@jgoppert this is ready to be tested now.

**Comment by jgoppert** [comment]
@bkueng I only see the attitude ground truth.

``` bash
Logging start time: 0:00:01, duration: 0:03:39
Dropouts: count: 1, total duration: 0.8 s, max: 829 ms, mean: 829 ms
Info Messages:
 ver_hw: SITL
 sys_name: PX4
 ver_sw: a1025ab75cfa81b71c8e52dd969801e47c203c2d
 time_ref_utc: 0

Name (multi id, message size in bytes)    number of data points, total bytes
 vehicle_attitude_groundtruth (0, 36)       20582     740952
 vehicle_attitude (0, 36)                   20582     740952
 actuator_outputs (0, 76)                    3790     288040
 telemetry_status (0, 36)                     219       7884
 vehicle_command (0, 65)                        2        130
 vehicle_status (0, 45)                      1094      49230
 commander_state (0, 9)                      2152      19368
 vehicle_attitude_setpoint (0, 55)          10360     569800
 vehicle_rates_setpoint (0, 24)             20582     493968
 actuator_controls_0 (0, 48)                10359     497232
 vehicle_local_position (0, 95)              2140     203300
 vehicle_local_position_setpoint (0, 48)     3864     185472
 vehicle_global_position (0, 70)             1955     136850
 vehicle_global_velocity_setpoint (0, 20)    1890      37800
 battery_status (0, 38)                       725      27550
 position_setpoint_triplet (0, 328)          1987     651736
 vision_position_estimate (0, 68)             519      35292
 optical_flow (0, 46)                        4024     185104
 distance_sensor (0, 27)                     4359     117693
 estimator_status (0, 309)                   4144    1280496
 ekf2_innovations (0, 132)                  10306    1360392
 control_state (0, 105)                     10359    1087695
 sensor_combined (0, 72)                    53176    3828672
 vehicle_gps_position (0, 91)                1097      99827
 vehicle_land_detected (0, 10)                  4         40
```

**Comment by bkueng** [comment]
Yes that's the only one we publish

**Comment by jgoppert** [comment]
@bkueng So ground truth, lat/lon/alt aren't recorded? If not, I think we should add it.
vehicle_attitude_groundtruth only has fieldss: rollspeed, pitchspeed, yawspeed, and q[0-3[

**Comment by bkueng** [comment]
Exactly. Sure, feel free to add them.

**Pull request merged**
