### PR TITLE
Add aion robotics r1 rover

### LINKED ISSUE #11955: Add model of Aion R1 rover to Gazebo
**Describe problem solved by the proposed feature**
The [Aion R1 Rover](http://docs.aionrobotics.com/en/latest/r1-ugv.html) is being used as a development platform for rover support in PX4. The current rover model in Gazebo does not accurately reflect this rover.

**Describe your preferred solution**
Add an accurate model of the Aion R1 rover for testing in Gazebo.

**Additional context**
The existing rover model in Gazebo is a Polaris golf cart.

### PR DESCRIPTION
**Pull request by Jaeyoung-Lim**
This PR adds a model of the differential rover in SITL based on the aion robotics r1 rover, where the models are from https://github.com/aionrobotics/r1_ugv_sim

Fixes https://github.com/PX4/Firmware/issues/11955

Screenshot from 2020-01-11 22-52-46

Remaining issues:
- The contact dynamics of the wheels make vehicle jump when the wheel spins too fast
- The vehicle is unable to turn on yaw inputs

### CODE REVIEW

**Comment by TSC21** [comment]
@Jaeyoung-Lim what do you think is required to fix the wheels contact dynamics? Try a different physics engine?

**Comment by Jaeyoung-Lim** [comment]
@TSC21 Could be an option. Since a lot of ROS implementations use a separate plugin for the skid steering dynamics I was wondering if we should do the same, but by removing the ROS dependencies

Should we try to bring in the skid steer drive plugin? http://docs.ros.org/jade/api/gazebo_plugins/html/gazebo__ros__skid__steer__drive_8cpp_source.html

**Comment by TSC21** [comment]
@Jaeyoung-Lim any news in this one?

**Comment by Jaeyoung-Lim** [comment]
@TSC21 No, I am a bit lost on this one. Do you have any ideas on how to proceed?

**Comment by TSC21** [comment]
> @TSC21 No, I am a bit lost on this one. Do you have any ideas on how to proceed?

Can you draft what issues are you facing? I know that the wheel dynamics are a bit flaky and it tends to drift right? Can you expose what are you facing and what solutions you have tried?

**Comment by Jaeyoung-Lim** [comment]
The current state of the PR is as the following.

**Blockers**
The vehicle contact dynamics are unable to reproduce the differential steering dynamics of the rover vehicle. 

**Solution that have been tried**
I have tried tuning the contact dynamics of the wheel but run into the following issues:
- When tuning the contact dynamics to have higher friction, this makes the vehicle jump and spin very fast
- When tuning the contact dynamics to have less friction, the vehicle is able to move forward / backwards but unable to turn when left and right motors have different speed

The original model uses the tire mesh as collision geometry and I have simplified in into a cylinder. The issue above occurs on both cases. 

**Other alternative Solution**
May be adding a separate differential dynamics plugin might make sense. The one that is provided by OSRF includes a controller that tracks velocity and has a dependency to ROS, therefore it needs to be ported for PX4 SITL

@TSC21

**Comment by Jaeyoung-Lim** [comment]
This might be a interesting solution for this problem: https://bitbucket.org/osrf/gazebo/pull-requests/2652/added-support-for-tracked-vehicles/diff

**Comment by TSC21** [comment]
> This might be a interesting solution for this problem: https://bitbucket.org/osrf/gazebo/pull-requests/2652/added-support-for-tracked-vehicles/diff

This seems to be available in Gazebo 9.12.

**Comment by Jaeyoung-Lim** [comment]
@TSC21 Finally got it running:

I am a bit unclear about the licensing, since the https://github.com/aionrobotics/r1_ugv_sim doesn't have a license written on it.

[Demo](https://youtu.be/cL7ZhvNvV3o)

**Comment by LorenzMeier** [comment]
@Jaeyoung-Lim Did you hear back from the manufacturer?

**Comment by Jaeyoung-Lim** [comment]
@LorenzMeier Yes, they said they will follow up with a license, but didn't mention wich one yet. (On 24th of April)

They also said they were not willing to "license" the mesh files, so I asked them if we can use a "simplified" mesh that doesn't include the parts separately

**Comment by LorenzMeier** [comment]
Ok. Could you please ask if we can go forward with this? This shouldn't be stale for three months.

**Comment by Jaeyoung-Lim** [comment]
@LorenzMeier At the moment, I believe the answer is no. Closing unless they come back otherwise

I will create a differential rover that is based on a different mesh if they confirm we cannot use even simplified mesh files

**Comment by jmachuca77** [comment]
Hi @LorenzMeier @Jaeyoung-Lim the licenses have been updated on the repos, should allow use of the meshes as long as they are not used for manufacturing, the meshes there are already simplified meshes. Please note the one you linked to is stale and you should be using these instead:

https://github.com/aionrobotics/aion_control
https://github.com/aionrobotics/aion_r1_description
https://github.com/aionrobotics/aion_r1_gazebo

**Comment by Jaeyoung-Lim** [comment]
@jmachuca77 Thanks! I have updated the license description in the `model.config` accordingly

**Review by TSC21 — APPROVED** [review]

**Pull request merged**
