### PR TITLE
Fix sweep cosine

### PR DESCRIPTION
**Pull request by EliaTarasov**
Fixes sweep cosine.

### CODE REVIEW

**Comment by EliaTarasov** [comment]
@TSC21 Technically this fix should be applied but in practice it doesn't change the behaviour noticeably. What's your opinion?

**Comment by EliaTarasov** [comment]
Closed as stale.

**Comment by TSC21** [comment]
Please reopen. As soon as possible it is reviewed.

**Review by TSC21 — APPROVED** [review]
This looks correct to me. @Jaeyoung-Lim any inputs?

**Review by Jaeyoung-Lim — APPROVED** [review]
LGTM!

**Comment by Jaeyoung-Lim** [comment]
Replaced with a rebase in #429 @EliaTarasov Hope thats okay for you

**Pull request closed without merging**
