### PR TITLE
Support SITL simulation for boat with usv_gazebo plugin

### PR DESCRIPTION
**Pull request by Jaeyoung-Lim**
This PR adds a PX4 SITL model for a boat using the `usv_gazebo` plugin.

The model is based on the `WAM-V` USV from the [osrf/vrx](https://bitbucket.org/osrf/vrx/src/default/) simulation.

The plugin is able to simulate / render waves as if the boat was in the ocean as shown below.
[BoatPX4SITL](https://youtu.be/HnL5HWe3vU0 "BoatPX4SITL")

### CODE REVIEW

**Comment by hamishwillee** [comment]
@Jaeyoung-Lim This probably should have associated docs in https://dev.px4.io/master/en/simulation/gazebo.html

... but we don't support boat right? At least there are no frames: https://dev.px4.io/master/en/airframes/airframe_reference.html#airframes-reference

If we're going to support boat we should consider minimum docs to make it work. At the moment we have lots of things that work, but the limited amount of information about them means that it it is not easy for people to use them - e.g. helicopter, rover etc.

**Comment by Jaeyoung-Lim** [comment]
@hamishwillee I have updated the PR in #409, the intention is that we eventually support boats, since this has been requested many times without any follow up

**Comment by hamishwillee** [comment]
@Jaeyoung-Lim That's great. As I'm sure you know, there is more to "supporting" than having an airframe in sitl/etc. Essentially people have to be able to do useful stuff with the "out of the box" experience, and have enough direction to create something of product quality. For copters we create that with out of the box configurations that get you to flying, assembly guides, and tuning guides.

**Comment by Jaeyoung-Lim** [comment]
@hamishwillee Thanks, I understand.

Currently I have no plans on using it on a real vehicle, but I believe there were a few on the rover call that wanted to try, but were blocked with limited SITL support. (You will need to swim if something went wrong) I am fine with not merging the boat support until someone tests this on a real vehicle. but ,hopefully this would enable some people that would

**Pull request closed without merging**
