### PR TITLE
Decrease motor constants of iris

### PR DESCRIPTION
**Pull request by Jaeyoung-Lim**
Decreased motor constants since the hover throttle was too low (20%). 

Discussion from: https://github.com/PX4/Firmware/pull/15569

### CODE REVIEW

**Review by jkflying — APPROVED** [review]

**Comment by MaEtUgR** [comment]
We found out that it was a mixer bug and reducing the power and hence increasing the necessary thrust demand per motor brought it wo the still working range of the mixer: https://github.com/PX4/Firmware/pull/15626
Can we give the iris power again? 70% hover thrust is not a very realistic "normal drone" since 2:1 thrust to weight ratio is a widely adopted requirement.

**Comment by Jaeyoung-Lim** [comment]
@MaEtUgR Do we want to revert this change? or do we want another value that satisfies the 2:1 rule?

Reverting it will make it 5:1

**Comment by MaEtUgR** [comment]
> Reverting it will make it 5:1

I didn't check, are you sure? If I remember correctly it had ~50% hover thrust and I would propose to have it somewhere in the range 35-50%. I prefer lower since that allows faster maneuvers. Should I do some tests and propose a value in a pr?

**Comment by Jaeyoung-Lim** [comment]
@MaEtUgR Yes please!

**Comment by MaEtUgR** [comment]
I tried e.g. `<motorConstant>5.0e-05</motorConstant>` and it seems the hover thrust estimator has some problems to converge 🤔 
image

But it also has some problems on the current value just less bad:
`<motorConstant>5.84e-06</motorConstant>`
image


This needs more investigation 😬  (JFYI @bresch)

**Pull request merged**
