### PR TITLE
travis: use catkin build tools

### PR DESCRIPTION
**Pull request by TSC21**

### CODE REVIEW

**Review by dagar — APPROVED** [review]

**Comment by dagar** [comment]
What about CATKIN_DEVEL_PREFIX instead of BUILD_ROS_INTERFACE?

**Comment by TSC21** [comment]
> What about CATKIN_DEVEL_PREFIX instead of BUILD_ROS_INTERFACE?

Why does one replace the other? The BUILD_ROS_INTERFACE is a Cmake option that allows building the ROS dependent plugins. You can catkin build without that option still.

**Comment by dagar** [comment]
My assumption is anyone building in a catkin workspace is using ROS. Using a standard flag to do something automatically is much better than having to know about a custom option in PX4 world.

**Comment by TSC21** [comment]
`catkin_tools` does not depend on ROS, though I do understand what you say. What do you suggest then to automate the process in order that the ROS dependent plugins only build under the `catkin`?

**Pull request merged**
