### PR TITLE
Fix wind topic names for vtols

### LINKED ISSUE #551: Windy world stuck on assertion failed
From the slack conversation with @julianoes and @Jaeyoung-Lim :

When running `HEADLESS=1 make px4_sitl gazebo_standard_vtol__windy` on current master (PX4 head is at 9ba2539e60, sitl_gazebo head is at ce1eca2), it gets stuck on a failed assertion: (same issue with `make px4_sitl gazebo_plane__windy`)

`thomas@thomas-N56VZ:~/git_folders/Firmware$ HEADLESS=1 make px4_sitl gazebo_standard_vtol__windy`
`[0/5] Performing build step for 'sitl_gazebo'`
`ninja: no work to do.`
`[4/5] cd /home/thomas/git_folders/Firm...olders/Firmware/build/px4_sitl_default`
`SITL ARGS`
`sitl_bin: /home/thomas/git_folders/Firmware/build/px4_sitl_default/bin/px4`
`debugger: none`
`program: gazebo`
`model: standard_vtol`
`world: windy`
`src_path: /home/thomas/git_folders/Firmware`
`build_path: /home/thomas/git_folders/Firmware/build/px4_sitl_default`
`GAZEBO_PLUGIN_PATH :/home/thomas/git_folders/Firmware/build/px4_sitl_default/build_gazebo`
`GAZEBO_MODEL_PATH :/home/thomas/git_folders/Firmware/Tools/sitl_gazebo/models`
`LD_LIBRARY_PATH /home/thomas/catkin_ws/devel/lib:/opt/ros/melodic/lib:/home/thomas/git_folders/Firmware/build/px4_sitl_default/build_gazebo`
`gzserver: /usr/include/boost/smart_ptr/shared_ptr.hpp:734: typename boost::detail::sp_member_access<T>::type boost::shared_ptr<T>::operator->() const [with T = const gazebo::msgs::Wind; typename boost::detail::sp_member_access<T>::type = const gazebo::msgs::Wind*]: Assertion `px != 0' failed.
`

Other worlds such as "empty" or "warehouse" instead of "windy" work.

To reproduce (hopefully), checkout PX4 master, run `make distclean` or `make clean` and `git submodule update --recursive --init` before `HEADLESS=1 make px4_sitl gazebo_standard_vtol__windy` on Ubuntu18.04 with Gazebo version 9.13.1

### PR DESCRIPTION
**Pull request by Jaeyoung-Lim**
**Motivation**
The wind topic names were not properly updated in vtol models after https://github.com/PX4/sitl_gazebo/pull/467 and the regression was caused by #490

Therefore resulting in a error shown in https://github.com/PX4/sitl_gazebo/issues/551

**Additional Context**
Fixes https://github.com/PX4/sitl_gazebo/issues/551

### CODE REVIEW

**Review by TSC21 — COMMENTED** [review]
Any reason for not calling it just `wind`?

**Comment by Jaeyoung-Lim** [comment]
@TSC21 That is actually why it was returning an error, since the world already has a wind topic published from gazebo by default, but the message definitions are different that is being used in the wind_plugin

**Comment by Jaeyoung-Lim** [comment]
@TSC21 Hi Nuno! Can we get this in?

**Review by TSC21 — APPROVED** [review]

**Comment by Jaeyoung-Lim** [comment]
@TSC21 Thanks!

**Comment by ThomasRigi** [comment]
@Jaeyoung-Lim Thanks for fixing this! The build process works now.

But... The airspeed reading does not show the wind anymore. It's always roughly equal to the ground speed:
https://logs.px4.io/plot_app?log=c130f864-5dfb-41c2-a077-b9a9c2abdc59

~~I'm going to open a new issue for this with some more details.~~ New issue: #556

**Pull request merged**
