### PR TITLE
pr-add normal gaussian distribution to wind force and direction

### PR DESCRIPTION
**Pull request by EliaTarasov**
This pr adds normal gaussian distribution to wind force and wind direction. 
Result: https://drive.google.com/open?id=1c4jpqSRXzqx94t36fVlpSpllU4TGzXi4

### CODE REVIEW

**Review by TSC21 — APPROVED** [review]

**Comment by EliaTarasov** [comment]
@TSC21 good to go?

**Comment by TSC21** [comment]
@LorenzMeier can we get your approval here?

**Comment by EliaTarasov** [comment]
@LorenzMeier can you say your opinion?

**Review by TSC21 — CHANGES_REQUESTED** [review]
@EliaTarasov I think it makes sense to apply the same to the wind gust. Also, there should be a max value for both wind and wind gust means, set by a parameter.

**Comment by EliaTarasov** [comment]
Discussion continues [ here](https://github.com/PX4/sitl_gazebo/pull/245)

**Pull request closed without merging**
