### PR TITLE
Implement gimbal controller as MAVLink gimbal v2 device

### PR DESCRIPTION
**Pull request by julianoes**
This adds a gimbal controller which communicates via MAVLink to PX4 and implements the gimbal v2 device interface as described in https://mavlink.io/en/services/gimbal_v2.html#how-to-implement-the-gimbal-device-interface.

### CODE REVIEW

**Review by Jaeyoung-Lim — COMMENTED** [review]
I tried running this with the latest master and get the following message:
```
Exception sending a message
Exception sending a message
Exception sending a message
Exception sending a message
Exception sending a message
Exception sending a message
Exception sending a message
Exception sending a message
Exception sending a message
Exception sending a message
Exception sending a message
Exception sending a message
Exception sending a message
Exception sending a message
Exception sending a message
Exception sending a message
Exception sending a message
Exception sending a message
Exception sending a message
```
Am I missing something?

To reproduce:
```
make px4_sitl gazebo_typhoon_h480
```

**Comment by julianoes** [comment]
@Jaeyoung-Lim thanks for testing. That's interesting. I'll see if I can reproduce it.

**Comment by julianoes** [comment]
@Jaeyoung-Lim I don't see that. It works for me.

**Comment by Jaeyoung-Lim** [comment]
@julianoes Hmm okay, I am on Ubuntu 18.04 / Gazebo9. Could it be a system issue?

I also didn't include https://github.com/PX4/PX4-Autopilot/pull/16734 if this is required

**Comment by julianoes** [comment]
@Jaeyoung-Lim oh, this won't work without the firmware change.

**Comment by Jaeyoung-Lim** [comment]
@julianoes What would be a good way to test this? Would the only way be using MAVSDK?

**Comment by julianoes** [comment]
@Jaeyoung-Lim 

You have to test https://github.com/PX4/PX4-Autopilot/pull/16734, and you can test it with this command in MAVSDK:

```
cmake -Bbuild/default cmake --build build/default -j8 && build/default/src/integration_tests/integration_tests_runner --gtest_filter="SitlTestGimbal.GimbalMove"
```
or:
```
cmake -Bbuild/default cmake --build build/default -j8 && build/default/src/integration_tests/integration_tests_runner --gtest_filter="SitlTestGimbal.GimbalAngles"
```

**Review by Jaeyoung-Lim — APPROVED** [review]
Thanks!

**Comment by farhangnaderi** [comment]
Was going over this, just tested, below is the link to a short video:

https://drive.google.com/file/d/1wBi8tL3FtScTLfBBuTFbbhFN31d4X0SM/view?usp=sharing

**Pull request merged**
