### PR TITLE
pr-enable wind plugin

### PR DESCRIPTION
**Pull request by EliaTarasov**
This pr enables wind plugin again.

### CODE REVIEW

**Comment by dagar** [comment]
Any idea why it was disabled?

**Comment by EliaTarasov** [comment]
No, i wonder why too. It is useful to have it.

**Comment by TSC21** [comment]
From what I know, the wind plugin was commented because it wasn't working as it should (or at all). If you confirm that it works as expected, then I don't see an issue bringing it.

**Comment by EliaTarasov** [comment]
I use it with multirotor. It works as expected except that `windForceVariance` and `windGustForceVariance` tags are not implemented. This could be add later on.

**Comment by EliaTarasov** [comment]
@TSC21 Is it good enough to proceed?

**Comment by TSC21** [comment]
I would like to see this working first. Can you please share a log or even a way of showing that the wind vectors are doing something?

**Comment by EliaTarasov** [comment]
Logs: https://review.px4.io/plot_app?log=d0cbee4f-1b05-4ff8-b6c3-bc7fc3881ca9
Video: https://drive.google.com/open?id=1udEwa72L53Ogb4zSuFYckVbJuSANF9sD

**Review by TSC21 — APPROVED** [review]
LGTM. @LorenzMeier anything against?

**Comment by mhkabir** [comment]
@RomanBapst @priseborough this might be useful to test and enable drag fusion by default on multirotor aircraft.

**Comment by EliaTarasov** [comment]
@LorenzMeier could you take a look at this?

**Pull request merged**
