### PR TITLE
Fix gazebo7 build failure

### PR DESCRIPTION
**Pull request by Jaeyoung-Lim**
This fixes the build failure for gazebo7 that was caused by API differences between 7 and higher versions

Reference: https://travis-ci.org/github/PX4/sitl_gazebo/jobs/699176964#L425

### CODE REVIEW

**Review by TSC21 — APPROVED** [review]
Thanks!

**Comment by TSC21** [comment]
@Jaeyoung-Lim seems it's not the only one: https://travis-ci.org/github/PX4/sitl_gazebo/jobs/700040027#L426

**Comment by Jaeyoung-Lim** [comment]
@TSC21 Totally missed that part. Hope this one is enough :crossed_fingers:

**Comment by LorenzMeier** [comment]
Why do we care about Gazebo 7 still? I think we can just take it out. We're at 9 minimum now and up to 11.

**Review by TSC21 — APPROVED** [review]

**Comment by TSC21** [comment]
> Why do we care about Gazebo 7 still? I think we can just take it out. We're at 9 minimum now and up to 11.

I would say we could deprecare it at the same time we deprecate our toolchain for 16.04.

**Pull request merged**
