### PR TITLE
Remove rubble and uneven world

### PR DESCRIPTION
**Pull request by Jaeyoung-Lim**
This PR removes `rubble.world` and `uneven.world` which seems like unnecessary worlds to have.

It is also not part of the make targets, and IMHO it is not worth adding.

### CODE REVIEW

**Comment by hamishwillee** [comment]
This will require removal from http://dev.px4.io/master/en/simulation/gazebo_worlds.html

Presumably someone needed these for something originally? Testing safe landing or similar? Do we know why they were here in the first place?

**Comment by Jaeyoung-Lim** [comment]
@hamishwillee I have removed it in https://github.com/PX4/Devguide/pull/1012 

I realized how useless the worlds were by trying it out. I really doubt that anybody would need it...

**Comment by hamishwillee** [comment]
Great!

**Comment by TSC21** [comment]
Fine with me!

**Review by TSC21 — APPROVED** [review]

**Pull request merged**
