### PR TITLE
fix hil: disable lockstep if HIL is enabled

### PR DESCRIPTION
**Pull request by bkueng**

### CODE REVIEW

**Comment by TSC21** [comment]
This should fix HIL not working right?

**Comment by bkueng** [comment]
Yes this is required, but I have not actually tested HIL with gazebo.

**Review by julianoes — APPROVED** [review]
Great thx.

**Comment by TSC21** [comment]
Can this be asserted first before merging?

**Comment by bkueng** [comment]
@TSC21 tested, and there were a couple more things required. Works now.

**Comment by TSC21** [comment]
> @TSC21 tested, and there were a couple more things required. Works now.

Awesome! Merging

**Pull request merged**
