### PR TITLE
function to load parameters for each model from xml file

### PR DESCRIPTION
**Pull request by korotkoves**

### CODE REVIEW

**Comment by TSC21** [comment]
@korotkoves this looks good to me but its usage should be preferentially documented. Can you please add some description on how to do it in https://github.com/PX4/Devguide/blob/master/en/simulation/gazebo.md? Thanks

**Comment by korotkoves** [comment]
Did you mean that I should document usage of multiple-sitl (that uses this modification of sitl_gazebo for work) ?
To document I should do pull request to https://github.com/PX4/Devguide/blob/master/en/simulation/gazebo.md ?

**Comment by TSC21** [comment]
Actually more like the usage and advantages of using loading parameters from a xml file in this case. For the other PR, yes that would be good also.

**Comment by korotkoves** [comment]
If shortly, loading parameters in such way allows use of one sdf model file (with basic model options and parameters) for all cloned instances of this model and differentiate properties(such as udp ports) for individual model instances.

**Comment by TSC21** [comment]
Sounds good. That explanation with an example on the Devguide would allow future users to use the same approach. This is just a way of not letting this fall into something considered unused.

**Comment by TSC21** [comment]
Also, please rebase the PR.

**Comment by korotkoves** [comment]
rebased

**Comment by TSC21** [comment]
@hamishwillee can you open an issue about this on the devguide so it can be tracked? The idea is to then close it with a PR. I will do it myself but if I have any doubts I will ping @korotkoves.

I am closing this since it is superseded by #199

**Comment by hamishwillee** [comment]
Great. I have responded to your docs question in https://github.com/acsl-mipt/multiple-sitl/issues/5

**Comment by TSC21** [comment]
@hamishwillee this is a different subject here: what it addresses here is the usage of `tinyxml` to parse parameters on XML files into C++ usable variables (how it works, why it should be used, why not that approach for some parameter loading on other models of `sitl_gazebo`).

**Comment by hamishwillee** [comment]
@TSC21 Sorry! Is this something that should be part of https://github.com/PX4/Devguide/issues/440 ?

**Comment by TSC21** [comment]
> @TSC21 Sorry! Is this something that should be part of PX4/Devguide#440 ?

It's almost related, but this is rather useful for parameter loading rather than generating models SDF files. Meaning this is used in runtime, not in build time as jinja or xacro.

**Comment by hamishwillee** [comment]
Thanks - created here: https://github.com/PX4/Devguide/issues/529

I'm not sure of the right place for the doc to live - but probably in https://dev.px4.io/en/simulation/gazebo.html#extending-and-customizing, or under the Gazebo document in the tree.

**Pull request closed without merging**
