### PR TITLE
Tidy gazebo tailsitter.sdf configuration.

### PR DESCRIPTION
**Pull request by grahamjamesaddis**
Colour the rotors as per the airframe reference and use the correct visuals for the clockwise rotors.

### CODE REVIEW

**Review by Jaeyoung-Lim — CHANGES_REQUESTED** [review]
Thanks for the contribution!

However, I think the color conventions are breaking how rotors on the other models are being colored(blue) .

Therefore, would it be possible to leave out the color changes from the PR?

**Comment by grahamjamesaddis** [comment]
In the original model there were three DarkGrey rotors and one Blue.

As the DarkGrey rotors were very difficult to see against the dark grey floor I changed them to make them easier to see.

I coloured them to match the rotor colours in the airframe reference, as I felt it made sense, rotors 1&2 blue ccw, 3&4 green cw.

https://docs.px4.io/master/en/airframes/airframe_reference.html#vtol-quad-tailsitter

If however it is preferred that they all be coloured blue, I can change them to that colour.

**Comment by Jaeyoung-Lim** [comment]
@grahamjamesaddis Yes, I think this should not be a model specific change. If we decide to do it this way, we should do it for all vehicles. However, I think it is more useful to set the colors to make the orientation of the vehicle more obvious visually, than making it visualize the motor layout of the vehicle. 

Therefore, I do prefer having an irregular pattern for the tailsitter compared to making the prop colors all blue. Especially for the tailsitter since the fuselage is symmetric. 

Would this make sense to you?

**Comment by grahamjamesaddis** [comment]
So we need to choose a convention:

For quad, y and multi-copters:
Perhaps red at the front, yellow at the rear, green in the middle?

For conventional aircraft, it probably is not important.

For multi-rotor tail-sitters, as above.

For twin-rotor tail-sitters we need to distinguish port and starboard. Any ideas?

**Comment by Jaeyoung-Lim** [comment]
> So we need to choose a convention:

Why? IMHO I don't see much value in this given that there is no standard convention. The images in the airframe configs are just visualizations for the context of the document. This doesn't mean that all vehicles/3D models need to follow the same color conventions.

**Comment by grahamjamesaddis** [comment]
I have coloured the rear/upper rotors Blue and the front/lower rotors Grey. They are now easily visible against the ground and sky in the default world.

I have also converted it to jinja.

**Review by Jaeyoung-Lim — APPROVED** [review]
Thanks!

**Pull request merged**
