### PR TITLE
Add gps_origin_plugin for broadcasting GPS origin of worlds 

### PR DESCRIPTION
**Pull request by Jaeyoung-Lim**
This PR adds the `gps_origin_plugin` where the gps origin of the world is broadcasted from the world file.

This enables spawning the same vehicle to different environments where the world is based on a real location so that the map in QGC matches the environment in the gazebo world.

This PR depends on the model - world spearation in https://github.com/PX4/sitl_gazebo/pull/414 and https://github.com/PX4/Firmware/pull/14166

As an example, I have created the `sonoma_raceway.world` to demonstrate how the GPS origin should be implemented in the world file

The world can be started by the following command
```
make px4_sitl gazebo_rover__sonoma_raceway
```

[Demo](https://youtu.be/caPbIHKRUCs)

### CODE REVIEW

**Review by TSC21 — COMMENTED** [review]
@Jaeyoung-Lim why not just extend the `gazebo_gps_plugin`?

**Comment by Jaeyoung-Lim** [comment]
@TSC21 Because the gps plugin is a model plugin. The gps_origin_plugin is a world plugin.

For example if we have more than one vehicle, or the vehicle is spawned separately from the world, it would be hard to deal with the extension of the gps plugin.

**Comment by TSC21** [comment]
Here's what we need: http://sdformat.org/spec?ver=1.6&elem=world#world_spherical_coordinates.

**Comment by Jaeyoung-Lim** [comment]
@TSC21 Thanks for the review and good find! I will move to the sdf approach. Makes much more sense

**Pull request closed without merging**
