### PR TITLE
CMakeLists improvements

### PR DESCRIPTION
**Pull request by nicolaerosia**
Hello,

Build is broken for me with the current CMakeLists.
Here are a set of changes which improve the CMakeLists.
Let me know if they work for you.

Regards

### CODE REVIEW

**Comment by nicolaerosia** [comment]
Any comments?

**Comment by LorenzMeier** [comment]
Ok, let me build this on OS X and see if it passes.

**Comment by chinlin0924** [comment]
when can this be merged in master?

**Comment by nicolaerosia** [comment]
Have you got the chance to test this?

**Comment by LorenzMeier** [comment]
Yes, it fails:

```
By not providing "FindEigen3.cmake" in CMAKE_MODULE_PATH this project has
  asked CMake to find a package configuration file provided by "Eigen3", but
  CMake did not find one.

  Could not find a package configuration file provided by "Eigen3" with any
  of the following names:

    Eigen3Config.cmake
    eigen3-config.cmake

  Add the installation prefix of "Eigen3" to CMAKE_PREFIX_PATH or set
  "Eigen3_DIR" to a directory containing one of the above files.  If "Eigen3"
  provides a separate development package or SDK, be sure it has been
  installed.
```

**Comment by LorenzMeier** [comment]
I expect similar issues for most of other workarounds I've put in. If you like to see this done "properly" we would need to spend the time to really fix it.

**Comment by nicolaerosia** [comment]
Can you tell me what cmake version do you have and what gazebo?
I don't use OS X, but I see Gazebo 7 is available on Mac. [0]
Is there any reason to use Gazebo 6 ?

[0] http://gazebosim.org/tutorials?tut=install_on_mac&cat=install

**Comment by LorenzMeier** [comment]
Yes. ROS Jade comes with 6, and we need to narrow down the configuration space for our developers. Many of them use ROS.

**Comment by nicolaerosia** [comment]
cmake --version please and can you share your lib64/cmake/gazebo/gazebo-config.cmake and ./lib64/cmake/gazebo/gazebo-config-version.cmake?

**Comment by LorenzMeier** [comment]
```
cmake version 3.5.0
```

and

```
# This is a basic version file for the Config-mode of find_package().
# It is used by write_basic_package_version_file() as input file for configure_file()
# to create a version-file which can be installed along a config.cmake file.
#
# The created file sets PACKAGE_VERSION_EXACT if the current version string and
# the requested version string are exactly the same and it sets
# PACKAGE_VERSION_COMPATIBLE if the current version is >= requested version,
# but only if the requested major version is the same as the current one.
# The variable CVF_VERSION must be set before calling configure_file().


set(PACKAGE_VERSION "6.5.1")

if(PACKAGE_VERSION VERSION_LESS PACKAGE_FIND_VERSION)
  set(PACKAGE_VERSION_COMPATIBLE FALSE)
else()

  if("6.5.1" MATCHES "^([0-9]+)\\.")
    set(CVF_VERSION_MAJOR "${CMAKE_MATCH_1}")
  else()
    set(CVF_VERSION_MAJOR "6.5.1")
  endif()

  if(PACKAGE_FIND_VERSION_MAJOR STREQUAL CVF_VERSION_MAJOR)
    set(PACKAGE_VERSION_COMPATIBLE TRUE)
  else()
    set(PACKAGE_VERSION_COMPATIBLE FALSE)
  endif()

  if(PACKAGE_FIND_VERSION STREQUAL PACKAGE_VERSION)
      set(PACKAGE_VERSION_EXACT TRUE)
  endif()
endif()


# if the installed or the using project don't have CMAKE_SIZEOF_VOID_P set, ignore it:
if("${CMAKE_SIZEOF_VOID_P}" STREQUAL "" OR "8" STREQUAL "")
   return()
endif()

# check that the installed version has the same 32/64bit-ness as the one which is currently searching:
if(NOT CMAKE_SIZEOF_VOID_P STREQUAL "8")
  math(EXPR installedBits "8 * 8")
  set(PACKAGE_VERSION "${PACKAGE_VERSION} (${installedBits}bit)")
  set(PACKAGE_VERSION_UNSUITABLE TRUE)
endif()
```

and

```
if (GAZEBO_CONFIG_INCLUDED)
  return()
endif()
set(GAZEBO_CONFIG_INCLUDED TRUE)
set(GAZEBO_VERSION 6.5)

set(GAZEBO_PLUGIN_PATH "/usr/local/Cellar/gazebo6/6.5.1/lib/gazebo-6.5/plugins")

# The media path contains the location on disk where images,
# materials scripts, shaders, and other related resources are stored.
set(GAZEBO_MEDIA_PATH "/usr/local/Cellar/gazebo6/6.5.1/share/gazebo-6.5/media")

set(GAZEBO_PLUGIN_PATH "/usr/local/Cellar/gazebo6/6.5.1/lib/gazebo-6.5/plugins")

# The media path contains the location on disk where images,
# materials scripts, shaders, and other related resources are stored.
set(GAZEBO_MEDIA_PATH "/usr/local/Cellar/gazebo6/6.5.1/share/gazebo-6.5/media")

#################################################
# GAZEBO_PROTO_PATH, GAZEBO_PROTO_INCLUDE_DIRS, and
# GAZEBO_PROTO_LIBRARIES
#
# These three variables allow Gazebo messages to be used in other projects.
#
# The following examples are for demonstration purposes and are
# incomplete. The first example shows how to use a Gazebo message in a
# custom  proto file. The second example shows how to run 'protoc' against
# custom proto files that make use Gazebo message definitions. The third
# example shows how to include the correct directory when compiling a library
# or executable that uses your custom messages.
#
# 1. Use a Gazebo message in a custom proto file:
#
# package my.msgs;
# import "vector3d.proto";
# 
# message MyMessage
# {
#   required gazebo.msgs.Vector3d p = 1;
# }
#
# 2. Run protoc from a CMakeLists.txt to generate your message's
#    header and source files:
#
#  add_custom_command(
#    OUTPUT
#      "${proto_filename}.pb.cc"
#      "${proto_filename}.pb.h"
#    COMMAND protoc
#    ARGS --proto_path ${GAZEBO_PROTO_PATH} ${proto_file_out}
#    COMMENT "Running C++ protocol buffer compiler on ${proto_filename}"
#    VERBATIM)
#
# 3. When compiling your library or executable, make sure to use the following
#    in the CMakeLists.txt file:
#
# include_directories(GAZEBO_PROTO_INCLUDE_DIRS)
# target_link_libraries(your_package GAZEBO_PROTO_LIBRARIES)
#
set(GAZEBO_PROTO_PATH
  "/usr/local/Cellar/gazebo6/6.5.1/include/gazebo-6.5/gazebo/msgs/proto")
find_library(gazebo_proto_msgs_lib gazebo_msgs
  PATHS "/usr/local/Cellar/gazebo6/6.5.1/lib" NO_DEFAULT_PATH)
list(APPEND GAZEBO_PROTO_LIBRARIES ${gazebo_proto_msgs_lib})
list(APPEND GAZEBO_PROTO_INCLUDE_DIRS
  "/usr/local/Cellar/gazebo6/6.5.1/include/gazebo-6.5/gazebo/msgs")
# End GAZEBO_PROTO_PATH, GAZEBO_PROTO_INCLUDE_DIRS, and
# GAZEBO_PROTO_LIBRARIES

list(APPEND GAZEBO_INCLUDE_DIRS /usr/local/Cellar/gazebo6/6.5.1/include)
list(APPEND GAZEBO_INCLUDE_DIRS /usr/local/Cellar/gazebo6/6.5.1/include/gazebo-6.5)

list(APPEND GAZEBO_LIBRARY_DIRS /usr/local/Cellar/gazebo6/6.5.1/lib)
list(APPEND GAZEBO_LIBRARY_DIRS /usr/local/Cellar/gazebo6/6.5.1/lib/gazebo-6.5/plugins)

list(APPEND GAZEBO_CFLAGS -I/usr/local/Cellar/gazebo6/6.5.1/include)
list(APPEND GAZEBO_CFLAGS -I/usr/local/Cellar/gazebo6/6.5.1/include/gazebo-6.5)

# Visual Studio enables c++11 support by default
if (NOT MSVC)
  list(APPEND GAZEBO_CXX_FLAGS -std=c++11)
endif()
if ("${CMAKE_CXX_COMPILER_ID}" MATCHES "Clang" AND
    "${CMAKE_SYSTEM_NAME}" MATCHES "Darwin")
  set(GAZEBO_CXX_FLAGS "${GAZEBO_CXX_FLAGS} -stdlib=libc++")
endif ()

foreach(lib gazebo;gazebo_client;gazebo_gui_building;gazebo_gui_viewers;gazebo_gui_model;gazebo_gui;gazebo_sensors;gazebo_rendering;gazebo_selection_buffer;gazebo_physics_bullet;gazebo_physics_simbody;gazebo_physics_ode;gazebo_physics;gazebo_ode;gazebo_transport;gazebo_msgs;gazebo_util;gazebo_common;gazebo_skyx;gazebo_gimpact;gazebo_opcode;gazebo_opende_ou;gazebo_math;gazebo_ccd)
  set(onelib "${lib}-NOTFOUND")
  find_library(onelib ${lib}
    PATHS /usr/local/Cellar/gazebo6/6.5.1/lib
    NO_DEFAULT_PATH
    )
  if(NOT onelib)
    message(FATAL_ERROR "Library '${lib}' in package GAZEBO is not installed properly")
  endif()
  list(APPEND GAZEBO_LIBRARIES ${onelib})
endforeach()

# Get the install prefix for OGRE
execute_process(COMMAND pkg-config --variable=prefix OGRE
  OUTPUT_VARIABLE OGRE_INSTALL_PREFIX OUTPUT_STRIP_TRAILING_WHITESPACE)

# Add the OGRE cmake path to CMAKE_MODULE_PATH
set(CMAKE_MODULE_PATH
  "${OGRE_INSTALL_PREFIX}/share/OGRE/cmake/modules;${OGRE_INSTALL_PREFIX}/lib/OGRE/cmake;${OGRE_INSTALL_PREFIX}/CMake;${CMAKE_MODULE_PATH}")

foreach(dep Boost;Protobuf;SDFormat;OGRE)
  if(NOT ${dep}_FOUND)
    if (${dep} MATCHES "Boost")
      find_package(Boost 1.40.0 REQUIRED thread signals system filesystem program_options regex iostreams date_time)
    else()
      find_package(${dep} REQUIRED)
    endif()
  endif()
  list(APPEND GAZEBO_INCLUDE_DIRS ${${dep}_INCLUDE_DIRS})

  # Protobuf needs to be capitalized to match PROTOBUF_LIBRARIES
  if (${dep} STREQUAL "Protobuf")
    string (TOUPPER ${dep} dep_lib)
  else()
    set (dep_lib ${dep})
  endif()

  list(APPEND GAZEBO_LIBRARIES ${${dep_lib}_LIBRARIES})

  # When including OGRE, also include the Terrain and Paging components
  if (${dep} STREQUAL "OGRE")
    list(APPEND GAZEBO_INCLUDE_DIRS ${OGRE_Terrain_INCLUDE_DIRS}
      ${OGRE_Paging_INCLUDE_DIRS})
    list(APPEND GAZEBO_LIBRARIES ${OGRE_Terrain_LIBRARIES}
      ${OGRE_Paging_LIBRARIES})
  endif()
endforeach()

find_package(ignition-math2 REQUIRED)
list(APPEND GAZEBO_INCLUDE_DIRS ${IGNITION-MATH_INCLUDE_DIRS})
list(APPEND GAZEBO_LIBRARY_DIRS ${IGNITION-MATH_LIBRARY_DIRS})
list(APPEND GAZEBO_LIBRARIES ${IGNITION-MATH_LIBRARIES})

list(APPEND GAZEBO_LDFLAGS -Wl,-rpath,/usr/local/Cellar/gazebo6/6.5.1/lib/gazebo-6.5/plugins)
list(APPEND GAZEBO_LDFLAGS -L/usr/local/Cellar/gazebo6/6.5.1/lib)
list(APPEND GAZEBO_LDFLAGS -L/usr/local/Cellar/gazebo6/6.5.1/lib/gazebo-6.5/plugins)

```

**Comment by nicolaerosia** [comment]
Hi,

Can you please test if this new commit works for you?
It seems that there's an issue with CMake in OS X
More details: https://github.com/ros-perception/perception_pcl/issues/106

**Comment by LorenzMeier** [comment]
The attempt to find Eigen3 results in a CMake error which terminates the build.

**Comment by nicolaerosia** [comment]
I'm sorry, I forgot the REQUIRED.

**Comment by LorenzMeier** [comment]
It worked, I rebased and applied, thanks!

**Pull request closed without merging**
