### PR TITLE
Three quad copter

### PR DESCRIPTION
**Pull request by shrit**
The following patch allow to create a simulation of 3 quadcopter. 
I am creating a pull request as @julianoes has requested in the forum.

The reason for this pull request is that there is no possibility to modify any original sdf files. I had to create different files and add my reset plugin inside. If I modify the original sdf files like iris.sdf or solo.sdf all of these modification are going to be deleted after the compiling using make px4_sitl gazebo_model.

A second point is that, we do not understand why only iris quadcopter created using xacro files rather than sdf file, I was not able to find any documentation that can explain the urdf rotor description. 

Finally,  If all these sdf files are generated after the complication process, is there any way to generalize this method to allow for users to generate there files at their need??

You can try this patch, I have created it as a way to create several quadcopter in Gazebo without the need for ROS, I would like to know if we can integrate a script that make the process automatically.

### CODE REVIEW

**Comment by tfoote** [comment]
I don't think that adding multiple copies of these drones makes sense in this repository. The current models serve as examples. If you need multiple there are lots of templating methods that can generate what you need. If we want to integrate something to this repository I'd suggest focusing on tools and scripts that are generally useful instead of adding multiple parallel models of a specific type.

**Comment by shrit** [comment]
I totally agree, this pull request to treat a bug proposed in the dronesdk forum, I do not want it to be integrated in the mainstream. I just want some explanation about the sdf files
Please you can read about this problem here: 
http://discuss.px4.io/t/bug-gazebo-sitl-starting-several-drone-with-mavlink/9438

**Comment by bkueng** [comment]
> I had to create different files and add my reset plugin inside.

Can you expand on that?

The reason to use the xacro files (according to my understanding) is to allow different parameterization, e.g. for `mavlink_udp_port`.

**Comment by shrit** [comment]
As I mentioned above I use gazebo to simulate 3 iris quadcopters, after each flight episode I need to reset the quadcopters to their initial positions. To do so, I have created a gazebo plugin using publish subscribe system that reset the quadcopter models. Then, I added this plugin inside the sdf file to all the quadcopters used in the simulation.
The original iris quadcopter did not see the included reset plugin. it seemed as the original quadcopter did not execute the sdf file, while other quadcopters had no problem adding the reset plugin to their sdf files.
I thought it is related to the xacro file, since it generates the sdf file. So I tried to modify the xacro file to add the plugin, but I did not succeed in doing it.
I understand from your answer the reason to use xacro file, but as I have noticed it is only the iris quadcopter that described in xacro file, all other quadcopters are described directly in sdf.

**Comment by bkueng** [comment]
> I thought it is related to the xacro file, since it generates the sdf file. So I tried to modify the xacro file to add the plugin, but I did not succeed in doing it.

Ok, so we need to resolve that. I'm pretty sure you can make that work since the xacro for the iris also uses different plugins.

**Comment by TSC21** [comment]
Closing this as this is not the solution for the presented problem.

**Pull request closed without merging**
