### PR TITLE
Enable Simulation of the Hippocampus (AUV from TUHH)

### PR DESCRIPTION
**Pull request by NRottmann**
Adding files which enable a simulation with the autonomous underwater
vehicle (AUV) from the Technical University Hamburg-Harburg.

For safety reasons I just added files (only had to add some lines to the CMakeFile). I have tested the simulation with gazebo-ROS and it works fine. For further information about our project feel free to ask or have a look at https://www.tuhh.de/mum/forschung/forschungsgebiete-und-projekte/flow-field-estimation-with-a-swarm-of-auvs.html

### CODE REVIEW

**Review by LorenzMeier — APPROVED** [review]

**Comment by LorenzMeier** [comment]
Awesome, thanks!

**Comment by TSC21** [comment]
Now I'm seeing something weird on this: why do we have `gazebo_motor_rotation.h` and `gazebo_motor_rotation.cpp`? They are basically copies of `gazebo_motor_model.h` and `gazebo_motor_model.cpp`. @NRottmann can you explain?

**Comment by TSC21** [comment]
@LorenzMeier do you confirm those are not needed?

**Comment by NRottmann** [comment]
@TSC21 
In gazebo_motor_model.cpp the forces and moments are updated. I am doing this for our HippoCampus in the gazebo_uuv_plugin.cpp. The gazebo_motor_rotation.cpp is just a copy of the gazebo_motor_model.cpp without applying forces onto the rotors (it just let the rotors spin, for animation). Since I did not want to change any of your code I thought this would be the easiest solution.

**Comment by TSC21** [comment]
We should not have this kind of duplication. Please as soon as you can check if you could add a condition based on the model being loaded.

**Comment by NRottmann** [comment]
@TSC21 I have checked it. I have deleted the duplication. See https://github.com/PX4/sitl_gazebo/pull/126

Thanks,
Nils

**Pull request merged**
