### PR TITLE
Added ksql airport model and example world

### PR DESCRIPTION
**Pull request by ahcorde**
Added ksql airport 
 - model 
 - example world

ksql

co-author: @tfoote

### CODE REVIEW

**Comment by tfoote** [comment]
Please test this out as is for feedback.  Before it's ready to merge we're going to move the models to be hosted at gazebosim.org/models so that the model data isn't stored here in this repository. But before we finalize the model upload there we'd like to get any feedback from reviews here.

**Comment by ahcorde** [comment]
```
    os.environ["PX4_HOME_LAT"] = "37.523640";
    os.environ["PX4_HOME_LON"] = "-122.255122";
    os.environ["PX4_HOME_ALT"] = "1.7";
```

**Comment by Jaeyoung-Lim** [comment]
@ahcorde Looks amazing! Thank you for the contribution!

Screenshot from 2020-03-26 17-36-40

**Review by Jaeyoung-Lim — APPROVED** [review]

**Comment by TSC21** [comment]
> @ahcorde Looks amazing! Thank you for the contribution!
> 
> Screenshot from 2020-03-26 17-36-40

@Jaeyoung-Lim having fun you are ahah

**Pull request merged**
