### PR TITLE
Improve linking of libraries

### PR DESCRIPTION
**Pull request by LukasWoodtli**
Modernize the CMake project to reduce the number of libraries that are linked to the targets.

### CODE REVIEW

**Comment by LorenzMeier** [comment]
Great attempt - but it doesn't build yet.

**Comment by TSC21** [comment]
@LukasWoodtli can you give another try here? Thank you!

**Comment by LukasWoodtli** [comment]
> @LukasWoodtli can you give another try here? Thank you!

I don’t have the developer environment set up on my mac. So I'm not sure if I manage to identify the problem on macOS.

**Comment by TSC21** [comment]
> > @LukasWoodtli can you give another try here? Thank you!
> > I don’t have the developer environment set up on my mac. So I'm not sure if I manage to identify the problem on macOS.

A good first try could be rebase it and see where it goes.

**Comment by Jaeyoung-Lim** [comment]
@TSC21 Do you think it would make sense to close this?

**Comment by LukasWoodtli** [comment]
> @TSC21 Do you think it would make sense to close this?

I think this can be closed. I didn’t manage to setup the dev environment on my Mac to fix the build.
And currently I don’t have any time to work on this.

**Comment by Jaeyoung-Lim** [comment]
@LukasWoodtli Thanks for the clarification, closing

**Pull request closed without merging**
