### PR TITLE
Added robot namespace to the model

### PR DESCRIPTION
**Pull request by Cavalletta98**
I added the robot namespace tag in order to see the camera topic under different namespaces

### CODE REVIEW

**Comment by Jaeyoung-Lim** [comment]
@Cavalletta98 Did it work?

**Comment by Cavalletta98** [comment]
@Jaeyoung-Lim yes

**Comment by Jaeyoung-Lim** [comment]
@Cavalletta98 Still not sure what this does - the robotNamespace tag is empty. What difference does it make to have an empty namespace tag?

**Comment by Cavalletta98** [comment]
@Jaeyoung-Lim If you spwan the model like this: `<node ns= "uav1" name="spawn_model" pkg="gazebo_ros" type="spawn_model" output="screen"
          args="-x 1 -sdf -database $(arg model) -model $(arg vehicle)_1">
    </node>
`
you will have the vehicle argument as namespace for the camera topic

**Comment by Jaeyoung-Lim** [comment]
@Cavalletta98 I know, but since you have made it empty, it doesnt do anything right?

**Comment by Cavalletta98** [comment]
@Jaeyoung-Lim It does what i explained to you. If you spwan the model as i show you before,you Will get vehicle argument before each camera topics as a namespace. It Is empty such that you can "pass" the namespace when you spwan the model

**Comment by Cavalletta98** [comment]
@Jaeyoung-Lim It is done like i did also for this [model](https://github.com/PX4/PX4-SITL_gazebo-classic/blob/main/models/fpv_cam/fpv_cam.sdf)

**Review by Jaeyoung-Lim — APPROVED** [review]

**Pull request merged**
