### PR TITLE
Add support for boat airframe in SITL

### PR DESCRIPTION
**Pull request by Jaeyoung-Lim**
Recently there has been interest on using PX4 on USV (unmanned surface vehicle) systems. This PR adapts the usv_dynamics plugin from the [vrx](https://bitbucket.org/osrf/vrx/src/default/) simulation and integrates the boat simulation into px4 SITL.

As PX4 does not officially support boats yet, I hope this PR becomes a initial step towards supporting such applications. 

The changes that were done compared to the original vrx project are as the following
- ROS dependencies have been removed
- Removed wave plugin dependencies (The original code segfaults if the wave plugin does not exist)
- Thrust plugin has been removed and the already existing `gazebo_motor_model`  is used
- Integrated into the mavlink HIL interface for px4 sitl

**Test Data Coverage**
The video below shows the WAM-V vehicle being controlled in manual mode.
ezgif com-video-to-gif(4)

**Additional Context**
This is a updated version of https://github.com/PX4/sitl_gazebo/pull/357

### CODE REVIEW

**Comment by Jaeyoung-Lim** [comment]
@TSC21 @bkueng This was merged in firmware already. Can we merge this to make it sync?

**Review by LorenzMeier — APPROVED** [review]

**Comment by LorenzMeier** [comment]
@Jaeyoung-Lim Please rebase

**Comment by Jaeyoung-Lim** [comment]
@LorenzMeier Done! Thanks!

**Comment by hamishwillee** [comment]
@Jaeyoung-Lim Associated docs PR?

**Comment by Jaeyoung-Lim** [comment]
@hamishwillee I haven't forgot! I will add it for sure :)

**Comment by Jaeyoung-Lim** [comment]
@hamishwillee Here it is : https://github.com/PX4/Devguide/pull/958

**Review by bkueng — APPROVED** [review]

**Comment by xdwgood** [comment]
@Jaeyoung-Lim  
Do you think this solution is acceptable? https://discuss.px4.io/t/error-about-gazebo-sitl-building/12019/11?u=xdwgood

I ran into the problem of consent today, and solved it by changing the code.
Or what is the correct solution?

**Comment by Jaeyoung-Lim** [comment]
@xdwgood It is not the correct solution. It is more likely the ifdef of gazebo version is maybe not enough https://github.com/PX4/sitl_gazebo/blob/master/src/gazebo_usv_dynamics_plugin.cpp#L251

Which version of gazebo are you running? We can build the plugins agains gazebo7 and gazebo9.

**Comment by xdwgood** [comment]
@Jaeyoung-Lim   gazebo9.11.0

**Comment by Jaeyoung-Lim** [comment]
@xdwgood Hmm that is strange. Could you open a separate issue?

**Comment by christopherSuts** [comment]
hello, what kind of airframe do you use on the QGroundControl?

**Comment by hamishwillee** [comment]
@christopherSuts Please don't necrobump issues. A question like this would be better asked in the discussion boards.

**Pull request merged**
