### PR TITLE
Fix dependencies on macOS

### PR DESCRIPTION
**Pull request by julianoes**
Now that gstreamer is required by default we actually need to fix getting these dependencies on macOS.

### CODE REVIEW

**Comment by TSC21** [comment]
@julianoes where's Gstreamer being installed here? Should it be installed using *homebrew*?

On my PR I have gstreamer1.0 being installed through package installer, which seems to do the trick as well. But if you confirm that it can also work using the installed version using *homebrew*, that's better.

**Review by TSC21 — APPROVED** [review]
I think it could make sense to still have some support for Sierra, but I think for now this should be enough.

**Comment by julianoes** [comment]
> I think it could make sense to still have some support for Sierra, but I think for now this should be enough.

To say it bluntly: I don't think we can cater for each and everyone and their outdated systems. If people are lazy to stay up to date it's their problem.

**Comment by julianoes** [comment]
And thanks for your help here and merging @TSC21!

**Comment by TSC21** [comment]
> > I think it could make sense to still have some support for Sierra, but I think for now this should be enough.
> 
> To say it bluntly: I don't think we can cater for each and everyone and their outdated systems. If people are lazy to stay up to date it's their problem.

Yeah, I guess you are right.

> And thanks for your help here and merging @TSC21!

No problem!

**Pull request merged**
