### PR TITLE
Pr tiltrotor

### PR DESCRIPTION
**Pull request by RomanBapst**
Working version of a quad tiltrotor.
I'd like to go over the sdf file and add some comments to make it a bit more easier to read.

### CODE REVIEW

**Comment by TSC21** [comment]
@RomanBapst I actually implemented a model for a tricopter but my approach was a bit different, since I actually added a tilt joint that influences directly the forces and the torques of the vehicle. Does the above approach actually change the tilt of the motors and in that way change how the vehicle behaves? Cause in my approach I actually had to make a small change on `gazebo_motor_model`.

**Comment by TSC21** [comment]
Actually, looking at it, I do prefer your approach. I am going to try it for the tricopter I have and if it works, I will do a PR with a tricopter model.

**Review by TSC21 — APPROVED** [review]

**Comment by TSC21** [comment]
Let me know when you have the comments finished so it can be merged.

**Comment by RomanBapst** [comment]
@TSC21 Hi! Yes, all 4 motors are actually tilted forward. A tiltrotor tricopter would be very easy to implement  as well. Looking forward to your model!

**Comment by TSC21** [comment]
> @TSC21 Hi! Yes, all 4 motors are actually tilted forward. A tiltrotor tricopter would be very easy to implement as well. Looking forward to your model!

Yeah actually I followed another approach because I was dumb enough to not to remember to add a parent link to the actual rotor link which position would change according to a position change. So it actually works but it's more of an hack than actually it was supposed to do (I was actually going to do a PR soon with it but glad I didn't eheh). So yeah this is a much better solution and will adopt it. Thanks!

**Comment by ganeshrk95** [comment]
@TSC21 Hey! Is the model for tricopter available for testing? Thanks. I am trying to make a model on my own, just wanted to have a reference.

**Comment by TSC21** [comment]
> @TSC21 Hey! Is the model for tricopter available for testing? Thanks. I am trying to make a model on my own, just wanted to have a reference.

Soon.

**Comment by ganeshrk95** [comment]
I have created a tricopter model with the 'tiltrotor' as reference. I have used the mixer file for tricopter from PX4/Firmware. I am not sure how to proceed after this. I have the model when I arm it , it rotates really fast, then slows down and stops sometimes. I am not able to use 'pwm test -c XX -p XXXX' command inside SITL to debug. It keeps throwing errors (even for standard models).

**Comment by TSC21** [comment]
@ganeshrk95 wait a couple of days and I will launch a PR wish will be put upstream and can be used as reference to any other tricopter model. Mine is currently working good, I am just taking care of the 3D model atm.

**Comment by ganeshrk95** [comment]
@TSC21 Thanks for the reply. Appreciate it.

**Comment by ganeshrk95** [comment]
@TSC21 Just wanted to check back.

**Comment by ganeshrk95** [comment]
@TSC21 Did you manage to finish the model? I have made the model, but motors are still behaving weirdly. Did you make any changes to the mixer files? This is what I did:
1. Changed the Firmware/src/modules/simulator/simulator_mavlink.cpp to add a case for MAV_TYPE_TRICOPTER with n=3
2. Added the tricopter_y+ mixer file into the ROMFS/SITL/mixers folder
3. Added an initiation file inside Firmware/POSIX-configs/SITL/init/ekf2 for tricopter in which I called the mixer file created in the previous step. The remaining parameters were taken from an iris. (I doubt if that could be the problem). I changed the parameter MAV_TYPE to 15 which is for a Y+ tricopter.
4. I have added a custom model with the SDF file created based on the tiltrotor with all the plugins.

Am I missing any steps here? @RomanBapst

**Comment by RomanBapst** [comment]
@TSC21 Could you please push the model even if the 3D model is not quite finished. I think it would help @ganeshrk95 a lot!

**Comment by TSC21** [comment]
Yeah I know I have been swamped with other stuff. Will do it tonight

**Comment by ganeshrk95** [comment]
@RomanBapst @TSC21 True. I have been stuck with this for a while now. Can't proceed forward from this error. Would be really helpful if you can push the code. Thanks.

**Comment by TSC21** [comment]
Ganesh I already sent you a message yesterday through Slack with a repo you can take a look into.

**Comment by ganeshrk95** [comment]
Thanks @TSC21. Appreciate it.

**Pull request merged**
