### PR TITLE
Add IF750A model

### PR DESCRIPTION
**Pull request by nicovanduijn**
This PR introduces a new simulation vehicle, the Auterion reference frame assembled by InspiredFlight, the IF750A.

The current model is heavily borrowing from the `iris` model, simply replacing the body with a respective .STL file. Some minor adjustments in scale and orientation, as well as propeller placement were necessary.

### CODE REVIEW

**Comment by bkueng** [comment]
@nicovanduijn can cherry-pick https://github.com/PX4/sitl_gazebo/commit/50541b1d5a6db070eb2da52d37655e1e61472afa? These are required changes to make it work.

**Comment by nicovanduijn** [comment]
Thanks for the catch with the model path, I broke it in my second commit.

Why is the world file required? Shouldn't that be independent of the model?

**Comment by bkueng** [comment]
> Why is the world file required? Shouldn't that be independent of the model?

It's independent, but PX4 SITL selects the same world file as the model's name.

**Comment by bkueng** [comment]
Rebased, fixed some things and merged.

**Pull request closed without merging**
