### PR TITLE
Add derived iris models to SITL testing

### PR DESCRIPTION
**Pull request by Jaeyoung-Lim**
This PR adds the following models to SITL testing
- `iris_dual_gps`

Related discussion from #504 

Edit: Removed `iris_opt_flow_mockup` from testing since some mission tests were failing

### CODE REVIEW

**Comment by Jaeyoung-Lim** [comment]
@julianoes Seems like mission tests fail for `iris_opt_flow_mockup` but not for `iris_dual_gps`.

Does this mean that #504 is no longer valid?

**Comment by julianoes** [comment]
> Does this mean that #504 is no longer valid?

I hope so. I will also retest locally.

**Comment by julianoes** [comment]
`iris_dual_gps` doesn't work for me yet:

gazebo11

Let me try to update to the latest Gazebo 11.

**Comment by Jaeyoung-Lim** [comment]
Interesting... I think there is only one gazebo11 release (gazebo 11.0.0)

**Comment by Jaeyoung-Lim** [comment]
@julianoes Can you try maybe updating the fedora gazebo release? Seems like it runs fine on gazebo11 with Ubuntu focal

**Comment by julianoes** [comment]
@Jaeyoung-Lim last time I tried Gazebo on Fedora it just stalled on loading the world. I can try again... The one that behaves weirdly is on Arch Linux.

**Comment by julianoes** [comment]
I've completely rebuilt all dependencies for Gazebo 11 on Arch Linux and the issue is the same. I'll probably close the PR if the problem is only affecting me.

**Comment by MaEtUgR** [comment]
I can confirm. I presumably have the same gazebo and dependency versions as @julianoes now and the default iris flies like it should but `make px4_sitl gazebo_iris_dual_gps` starts with the propellers inside the drone (zero coordinates body frame?) and they start turning around the motors which results in a very strange movement similar to what is in the gif above.

**Comment by Jaeyoung-Lim** [comment]
@julianoes Can we get this in?

**Comment by julianoes** [comment]
@Jaeyoung-Lim does it work now?

**Comment by Jaeyoung-Lim** [comment]
@julianoes On fedora I am not sure, but this is just adding it to CI on Ubuntu focal, so I would prefer if we can get it in so it gets tested

**Review by julianoes — APPROVED** [review]
If it works on Ubuntu that's fine.

**Pull request merged**
