### PR TITLE
travis: macOS: update Xcode to 10.1

### PR DESCRIPTION
**Pull request by TSC21**

### CODE REVIEW

**Comment by TSC21** [comment]
Current blocker: https://github.com/osrf/homebrew-simulation/pull/524

**Comment by julianoes** [comment]
@TSC21 looks like the blocker has been merged.

**Comment by TSC21** [comment]
It does but the problem seems to subsist in another place.

**Comment by TSC21** [comment]
@julianoes all good now with macOS builds. Merging

**Pull request merged**
