### PR TITLE
PX4/Firmware #4076 Added support for setting initial GPS value based …

### PR DESCRIPTION
**Pull request by dustingooding**
…on Gazebo world's spherical coordinates.

My editor also had some auto-formatting suggestions that I didn't disagree with.

### CODE REVIEW

**Comment by dustingooding** [comment]
By default, Gazebo provides (lat,lon) of (0,0) in the standard empty.world.

If you use a custom world file that looks something like this, you'll get Zurich:

```
<?xml version="1.0" ?>
<sdf version="1.5">
  <world name="default">
    <spherical_coordinates>
      <surface_model>EARTH_WGS84</surface_model>
      <latitude_deg>47.397742</latitude_deg>
      <longitude_deg>8.545594</longitude_deg>
      <elevation>488.0</elevation>
      <heading_deg>0</heading_deg>
    </spherical_coordinates>
    <!-- A global light source -->
    <include>
      <uri>model://sun</uri>
    </include>
    <!-- A ground plane -->
    <include>
      <uri>model://ground_plane</uri>
    </include>
    <include>
      <uri>model://iris</uri>
    </include>
  </world>
</sdf>
```

**Comment by nicolaerosia** [comment]
Hello,

This is nice.
Another improvement would be to get rid of this boilerplate code and just use the GPS Plugin from gazebo. (GpsSensor.cc)
If you want to investigate further:
$ gzserver --verbose test/worlds/dem_gps.world
$ gzclient --verbose
$ gz topic --echo /gazebo/default/box1/link/gps

**Comment by nicolaerosia** [comment]
Take a look here, I've changed it to use the Gazebo GPS Sensor:
https://github.com/nicolaerosia/sitl_gazebo/commits/feature/gazebo_gps

**Comment by dustingooding** [comment]
I'm all for closing this and using @nicolaerosia's feature/gazebo_gps.  Thanks!

**Comment by nicolaerosia** [comment]
@dustingooding , thanks but please be aware that I'm a newbie regarding PX4 and I think I might have bricked something. The Gazebo coordinate system is different than the one PX4 expects.
If you can test, please let me know how it works.

**Comment by nicolaerosia** [comment]
Another issue is the magnetic field https://github.com/nicolaerosia/sitl_gazebo/blob/master/src/gazebo_mavlink_interface.cpp#L113-L121

I will need to take a look at how others deal with it. If you have any idea, plese let me know :+1:

**Comment by LorenzMeier** [comment]
@nicolaerosia Did you figure out the magnetic field by now? I'm trying to work out what the correct order is to bring your work in.

**Comment by nicolaerosia** [comment]
@LorenzMeier I was looking into why PX4 is not working ok with Gazebo GPS plugin. It turns out I was using bad precision values.
I haven't had the time to look into magnetic field but I want to take a look at hector_gazebo and see how they did it, maybe even copy it. [0] But I will need to take a look @PX4 and understand how it expects the data.

[0] https://github.com/tu-darmstadt-ros-pkg/hector_gazebo/blob/indigo-devel/hector_gazebo_plugins/src/gazebo_ros_magnetic.cpp

**Pull request closed without merging**
